<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wssutil="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:tns="http://www.openuri.org/" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" name="CloseCreditCardStandingOrder" targetNamespace="http://www.openuri.org/">
<documentation>Straight Through Routing</documentation>
  <types>
    <xsd:schema>
<xsd:import namespace="http://www.openuri.org/" schemaLocation="http___integration_80_CreditCardProcesses_kfh_creditcard_standingorder_processes_CloseCreditCardStandingOrder.jpd_xsd=1"/>
</xsd:schema>
  </types>
  <message name="removeCreditCardStandingOrder">
    <part name="parameters" element="tns:removeCreditCardStandingOrder">
    </part>
  </message>
  <message name="removeCreditCardStandingOrderResponse">
    <part name="parameters" element="tns:removeCreditCardStandingOrderResponse">
    </part>
  </message>
  <portType name="CloseCreditCardStandingOrder">
    <operation name="removeCreditCardStandingOrder">
      <input message="tns:removeCreditCardStandingOrder" wsam:Action="http://www.openuri.org/CloseCreditCardStandingOrder/removeCreditCardStandingOrderRequest">
    </input>
      <output message="tns:removeCreditCardStandingOrderResponse" wsam:Action="http://www.openuri.org/CloseCreditCardStandingOrder/removeCreditCardStandingOrderResponse">
    </output>
    </operation>
  </portType>
  <binding name="CloseCreditCardStandingOrderSoapBinding" type="tns:CloseCreditCardStandingOrder">
    <wsp:PolicyReference URI="#policy"/>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="removeCreditCardStandingOrder">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="WLS_CloseCreditCardStandingOrder">
    <port name="CloseCreditCardStandingOrderSoap5" binding="tns:CloseCreditCardStandingOrderSoapBinding">
      <soap:address location="https://soa_apigw/ws/WLS_CloseCreditCardStandingOrder.CloseCreditCardStandingOrderSoap/1.0"/>
    </port>
    <port name="CloseCreditCardStandingOrderSoap4" binding="tns:CloseCreditCardStandingOrderSoapBinding">
      <soap:address location="https://integration/ws/WLS_CloseCreditCardStandingOrder/1.0"/>
    </port>
    <port name="CloseCreditCardStandingOrderSoap7" binding="tns:CloseCreditCardStandingOrderSoapBinding">
      <soap:address location="http://FZVDSOAAP05:6655/kfhsoa/ws/CloseCreditCardStandingOrder/1.0"/>
    </port>
    <port name="CloseCreditCardStandingOrderSoap6" binding="tns:CloseCreditCardStandingOrderSoapBinding">
      <soap:address location="https://soa_apigw/ws/WLS_CloseCreditCardStandingOrder/1.0"/>
    </port>
    <port name="CloseCreditCardStandingOrderSoap9" binding="tns:CloseCreditCardStandingOrderSoapBinding">
      <soap:address location="https://soa_apigw/kfhsoa/ws/CloseCreditCardStandingOrder/1.0"/>
    </port>
    <port name="CloseCreditCardStandingOrderSoap8" binding="tns:CloseCreditCardStandingOrderSoapBinding">
      <soap:address location="https://integration/kfhsoa/ws/CloseCreditCardStandingOrder/1.0"/>
    </port>
    <port name="CloseCreditCardStandingOrderSoap" binding="tns:CloseCreditCardStandingOrderSoapBinding">
      <soap:address location="http://FZVDSOAAP05:6655/ws/WLS_CloseCreditCardStandingOrder.CloseCreditCardStandingOrderSoap/1.0"/>
    </port>
    <port name="CloseCreditCardStandingOrderSoap3" binding="tns:CloseCreditCardStandingOrderSoapBinding">
      <soap:address location="https://integration/ws/WLS_CloseCreditCardStandingOrder.CloseCreditCardStandingOrderSoap/1.0"/>
    </port>
    <port name="CloseCreditCardStandingOrderSoap2" binding="tns:CloseCreditCardStandingOrderSoapBinding">
      <soap:address location="http://FZVDSOAAP05:6655/ws/WLS_CloseCreditCardStandingOrder/1.0"/>
    </port>
  </service>
    <wsp:UsingPolicy wsu:Required="true"/>
    <wsp1_2:Policy wsu:Id="policy">
<ns1:SupportingTokens xmlns:ns1="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200512">
<wsp1_2:Policy>
<ns1:UsernameToken ns1:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200512/IncludeToken/AlwaysToRecipient">
<wsp1_2:Policy>
<ns1:WssUsernameToken10/>
</wsp1_2:Policy>
</ns1:UsernameToken>
</wsp1_2:Policy>
</ns1:SupportingTokens>
</wsp1_2:Policy>
</definitions>