//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerFinancialPositionServiceReference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class Exception
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class creditCardApplications
    {
        
        private string creditCardNumberField;
        
        private double limitField;
        
        private string accountNumberField;
        
        private string civilIDField;
        
        private string cardStatusField;
        
        private double murabahaInstallmentsField;
        
        private string cardTypeField;
        
        private string expiryField;
        
        private double reInstallmentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string creditCardNumber
        {
            get
            {
                return this.creditCardNumberField;
            }
            set
            {
                this.creditCardNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double limit
        {
            get
            {
                return this.limitField;
            }
            set
            {
                this.limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string accountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string civilID
        {
            get
            {
                return this.civilIDField;
            }
            set
            {
                this.civilIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string cardStatus
        {
            get
            {
                return this.cardStatusField;
            }
            set
            {
                this.cardStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double murabahaInstallments
        {
            get
            {
                return this.murabahaInstallmentsField;
            }
            set
            {
                this.murabahaInstallmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string cardType
        {
            get
            {
                return this.cardTypeField;
            }
            set
            {
                this.cardTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string expiry
        {
            get
            {
                return this.expiryField;
            }
            set
            {
                this.expiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double reInstallments
        {
            get
            {
                return this.reInstallmentsField;
            }
            set
            {
                this.reInstallmentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class realEstateApplications
    {
        
        private double installmentAmountField;
        
        private string realEstateTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double installmentAmount
        {
            get
            {
                return this.installmentAmountField;
            }
            set
            {
                this.installmentAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string realEstateType
        {
            get
            {
                return this.realEstateTypeField;
            }
            set
            {
                this.realEstateTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class tradingApplications
    {
        
        private double installmentAmountField;
        
        private string invoiceNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double installmentAmount
        {
            get
            {
                return this.installmentAmountField;
            }
            set
            {
                this.installmentAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string invoiceNumber
        {
            get
            {
                return this.invoiceNumberField;
            }
            set
            {
                this.invoiceNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class financialPositionDTO
    {
        
        private bool wasTradingCheckSuccessfulField;
        
        private bool wasRealEstateCheckSuccessfulField;
        
        private tradingApplications[] tradingApplicationsField;
        
        private realEstateApplications[] realEstateApplicationsField;
        
        private creditCardApplications[] creditCardApplicationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool wasTradingCheckSuccessful
        {
            get
            {
                return this.wasTradingCheckSuccessfulField;
            }
            set
            {
                this.wasTradingCheckSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool wasRealEstateCheckSuccessful
        {
            get
            {
                return this.wasRealEstateCheckSuccessfulField;
            }
            set
            {
                this.wasRealEstateCheckSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TradingApplications", IsNullable=false)]
        public tradingApplications[] tradingApplications
        {
            get
            {
                return this.tradingApplicationsField;
            }
            set
            {
                this.tradingApplicationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RealEstateApplications", IsNullable=false)]
        public realEstateApplications[] realEstateApplications
        {
            get
            {
                return this.realEstateApplicationsField;
            }
            set
            {
                this.realEstateApplicationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CreditCardApplications", IsNullable=false)]
        public creditCardApplications[] creditCardApplications
        {
            get
            {
                return this.creditCardApplicationsField;
            }
            set
            {
                this.creditCardApplicationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(customerCreditInformationReport))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class operationResult
    {
        
        private bool isSuccessfulField;
        
        private string statusField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool isSuccessful
        {
            get
            {
                return this.isSuccessfulField;
            }
            set
            {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class customerCreditInformationReport : operationResult
    {
        
        private string ciNetTransactionNumberField;
        
        private string ciNetXMLResponseField;
        
        private string civilIDField;
        
        private byte[] creditReportPdfField;
        
        private string requestIDField;
        
        private string xmlReportIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ciNetTransactionNumber
        {
            get
            {
                return this.ciNetTransactionNumberField;
            }
            set
            {
                this.ciNetTransactionNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ciNetXMLResponse
        {
            get
            {
                return this.ciNetXMLResponseField;
            }
            set
            {
                this.ciNetXMLResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string civilID
        {
            get
            {
                return this.civilIDField;
            }
            set
            {
                this.civilIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=3)]
        public byte[] creditReportPdf
        {
            get
            {
                return this.creditReportPdfField;
            }
            set
            {
                this.creditReportPdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string requestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string xmlReportID
        {
            get
            {
                return this.xmlReportIDField;
            }
            set
            {
                this.xmlReportIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ciNetReportRequestVo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ciNetCommReportRequestVo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ciNetActionRequestVo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class ciNetAuthVo
    {
        
        private string secretField;
        
        private string userIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string secret
        {
            get
            {
                return this.secretField;
            }
            set
            {
                this.secretField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string userID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class ciNetReportRequestVo : ciNetAuthVo
    {
        
        private string amountOfFinanceField;
        
        private string cirTypeField;
        
        private string civilIDField;
        
        private byte[] consentFormField;
        
        private string creditLimitField;
        
        private string cultureInfoField;
        
        private string durationOFagreementField;
        
        private string durationUnitField;
        
        private string fileExtensionField;
        
        private string fileNameField;
        
        private string monthlySalaryField;
        
        private string occupationField;
        
        private string otherIncomeField;
        
        private string paymentAmountField;
        
        private string paymentFrequencyField;
        
        private string portfolioTypeField;
        
        private string purposeCodeField;
        
        private string reasonForNewInquiryField;
        
        private string relationToAccountField;
        
        private string reportTypeField;
        
        private string requestIDField;
        
        private string requestXMLStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string amountOfFinance
        {
            get
            {
                return this.amountOfFinanceField;
            }
            set
            {
                this.amountOfFinanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cirType
        {
            get
            {
                return this.cirTypeField;
            }
            set
            {
                this.cirTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string civilID
        {
            get
            {
                return this.civilIDField;
            }
            set
            {
                this.civilIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=3)]
        public byte[] consentForm
        {
            get
            {
                return this.consentFormField;
            }
            set
            {
                this.consentFormField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string creditLimit
        {
            get
            {
                return this.creditLimitField;
            }
            set
            {
                this.creditLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string cultureInfo
        {
            get
            {
                return this.cultureInfoField;
            }
            set
            {
                this.cultureInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string durationOFagreement
        {
            get
            {
                return this.durationOFagreementField;
            }
            set
            {
                this.durationOFagreementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string durationUnit
        {
            get
            {
                return this.durationUnitField;
            }
            set
            {
                this.durationUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string fileExtension
        {
            get
            {
                return this.fileExtensionField;
            }
            set
            {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string monthlySalary
        {
            get
            {
                return this.monthlySalaryField;
            }
            set
            {
                this.monthlySalaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string occupation
        {
            get
            {
                return this.occupationField;
            }
            set
            {
                this.occupationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string otherIncome
        {
            get
            {
                return this.otherIncomeField;
            }
            set
            {
                this.otherIncomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string paymentAmount
        {
            get
            {
                return this.paymentAmountField;
            }
            set
            {
                this.paymentAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string paymentFrequency
        {
            get
            {
                return this.paymentFrequencyField;
            }
            set
            {
                this.paymentFrequencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string portfolioType
        {
            get
            {
                return this.portfolioTypeField;
            }
            set
            {
                this.portfolioTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string purposeCode
        {
            get
            {
                return this.purposeCodeField;
            }
            set
            {
                this.purposeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string reasonForNewInquiry
        {
            get
            {
                return this.reasonForNewInquiryField;
            }
            set
            {
                this.reasonForNewInquiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string relationToAccount
        {
            get
            {
                return this.relationToAccountField;
            }
            set
            {
                this.relationToAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string reportType
        {
            get
            {
                return this.reportTypeField;
            }
            set
            {
                this.reportTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string requestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string requestXMLString
        {
            get
            {
                return this.requestXMLStringField;
            }
            set
            {
                this.requestXMLStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class ciNetCommReportRequestVo : ciNetAuthVo
    {
        
        private string cirTypeField;
        
        private string civilIDField;
        
        private byte[] consentFormField;
        
        private string cultureInfoField;
        
        private string fileExtensionField;
        
        private string fileNameField;
        
        private string idCodeField;
        
        private string idvalueField;
        
        private string inquiryTypeField;
        
        private string purposeCodeField;
        
        private string requestIDField;
        
        private string requestXMLStringField;
        
        private string responseTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cirType
        {
            get
            {
                return this.cirTypeField;
            }
            set
            {
                this.cirTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string civilID
        {
            get
            {
                return this.civilIDField;
            }
            set
            {
                this.civilIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] consentForm
        {
            get
            {
                return this.consentFormField;
            }
            set
            {
                this.consentFormField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string cultureInfo
        {
            get
            {
                return this.cultureInfoField;
            }
            set
            {
                this.cultureInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fileExtension
        {
            get
            {
                return this.fileExtensionField;
            }
            set
            {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string idCode
        {
            get
            {
                return this.idCodeField;
            }
            set
            {
                this.idCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string idvalue
        {
            get
            {
                return this.idvalueField;
            }
            set
            {
                this.idvalueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string inquiryType
        {
            get
            {
                return this.inquiryTypeField;
            }
            set
            {
                this.inquiryTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string purposeCode
        {
            get
            {
                return this.purposeCodeField;
            }
            set
            {
                this.purposeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string requestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string requestXMLString
        {
            get
            {
                return this.requestXMLStringField;
            }
            set
            {
                this.requestXMLStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string responseType
        {
            get
            {
                return this.responseTypeField;
            }
            set
            {
                this.responseTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class ciNetActionRequestVo : ciNetAuthVo
    {
        
        private string accountNoField;
        
        private string agreementDurationField;
        
        private string applicationStatusField;
        
        private string civilIDField;
        
        private string creditLimitField;
        
        private string durationUnitField;
        
        private string financeAmountField;
        
        private string monthlySalaryField;
        
        private string occupationField;
        
        private string paymentAmountField;
        
        private string paymentFrequencyField;
        
        private string portfolioTypeField;
        
        private string requestIDField;
        
        private string requestXMLStringField;
        
        private string transactionNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string accountNo
        {
            get
            {
                return this.accountNoField;
            }
            set
            {
                this.accountNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string agreementDuration
        {
            get
            {
                return this.agreementDurationField;
            }
            set
            {
                this.agreementDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string applicationStatus
        {
            get
            {
                return this.applicationStatusField;
            }
            set
            {
                this.applicationStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string civilID
        {
            get
            {
                return this.civilIDField;
            }
            set
            {
                this.civilIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string creditLimit
        {
            get
            {
                return this.creditLimitField;
            }
            set
            {
                this.creditLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string durationUnit
        {
            get
            {
                return this.durationUnitField;
            }
            set
            {
                this.durationUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string financeAmount
        {
            get
            {
                return this.financeAmountField;
            }
            set
            {
                this.financeAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string monthlySalary
        {
            get
            {
                return this.monthlySalaryField;
            }
            set
            {
                this.monthlySalaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string occupation
        {
            get
            {
                return this.occupationField;
            }
            set
            {
                this.occupationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string paymentAmount
        {
            get
            {
                return this.paymentAmountField;
            }
            set
            {
                this.paymentAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string paymentFrequency
        {
            get
            {
                return this.paymentFrequencyField;
            }
            set
            {
                this.paymentFrequencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string portfolioType
        {
            get
            {
                return this.portfolioTypeField;
            }
            set
            {
                this.portfolioTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string requestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string requestXMLString
        {
            get
            {
                return this.requestXMLStringField;
            }
            set
            {
                this.requestXMLStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string transactionNo
        {
            get
            {
                return this.transactionNoField;
            }
            set
            {
                this.transactionNoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.openuri.org/", ConfigurationName="CustomerFinancialPositionServiceReference.CustomerFinancialPositionService")]
    public interface CustomerFinancialPositionService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/CustomerFinancialPositionService/getCustomerCiNetDutiesReq" +
            "uest", ReplyAction="http://www.openuri.org/CustomerFinancialPositionService/getCustomerCiNetDutiesRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ciNetAuthVo))]
        System.Threading.Tasks.Task<CustomerFinancialPositionServiceReference.getCustomerCiNetDutiesResponse> getCustomerCiNetDutiesAsync(CustomerFinancialPositionServiceReference.getCustomerCiNetDutiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/CustomerFinancialPositionService/approveOrRejectCiNetInqui" +
            "ryRequest", ReplyAction="http://www.openuri.org/CustomerFinancialPositionService/approveOrRejectCiNetInqui" +
            "ryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ciNetAuthVo))]
        System.Threading.Tasks.Task<CustomerFinancialPositionServiceReference.approveOrRejectCiNetInquiryResponse> approveOrRejectCiNetInquiryAsync(CustomerFinancialPositionServiceReference.approveOrRejectCiNetInquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/CustomerFinancialPositionService/getCustomerDutiesRequest", ReplyAction="http://www.openuri.org/CustomerFinancialPositionService/getCustomerDutiesResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(CustomerFinancialPositionServiceReference.Exception), Action="http://www.openuri.org/CustomerFinancialPositionService/getCustomerDuties/Fault/E" +
            "xception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ciNetAuthVo))]
        System.Threading.Tasks.Task<CustomerFinancialPositionServiceReference.getCustomerDutiesResponse> getCustomerDutiesAsync(CustomerFinancialPositionServiceReference.getCustomerDutiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/CustomerFinancialPositionService/getCustomerCiNetCommercia" +
            "lDutiesRequest", ReplyAction="http://www.openuri.org/CustomerFinancialPositionService/getCustomerCiNetCommercia" +
            "lDutiesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ciNetAuthVo))]
        System.Threading.Tasks.Task<CustomerFinancialPositionServiceReference.getCustomerCiNetCommercialDutiesResponse> getCustomerCiNetCommercialDutiesAsync(CustomerFinancialPositionServiceReference.getCustomerCiNetCommercialDutiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/CustomerFinancialPositionService/getCiNetLookupDataRequest" +
            "", ReplyAction="http://www.openuri.org/CustomerFinancialPositionService/getCiNetLookupDataRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ciNetAuthVo))]
        System.Threading.Tasks.Task<CustomerFinancialPositionServiceReference.getCiNetLookupDataResponse> getCiNetLookupDataAsync(CustomerFinancialPositionServiceReference.getCiNetLookupDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerCiNetDuties", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getCustomerCiNetDutiesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public CustomerFinancialPositionServiceReference.ciNetReportRequestVo ciNetReportRequest;
        
        public getCustomerCiNetDutiesRequest()
        {
        }
        
        public getCustomerCiNetDutiesRequest(CustomerFinancialPositionServiceReference.ciNetReportRequestVo ciNetReportRequest)
        {
            this.ciNetReportRequest = ciNetReportRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerCiNetDutiesResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getCustomerCiNetDutiesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public CustomerFinancialPositionServiceReference.customerCreditInformationReport getCustomerCiNetDutiesResult;
        
        public getCustomerCiNetDutiesResponse()
        {
        }
        
        public getCustomerCiNetDutiesResponse(CustomerFinancialPositionServiceReference.customerCreditInformationReport getCustomerCiNetDutiesResult)
        {
            this.getCustomerCiNetDutiesResult = getCustomerCiNetDutiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="approveOrRejectCiNetInquiry", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class approveOrRejectCiNetInquiryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public CustomerFinancialPositionServiceReference.ciNetActionRequestVo actionRequest;
        
        public approveOrRejectCiNetInquiryRequest()
        {
        }
        
        public approveOrRejectCiNetInquiryRequest(CustomerFinancialPositionServiceReference.ciNetActionRequestVo actionRequest)
        {
            this.actionRequest = actionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="approveOrRejectCiNetInquiryResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class approveOrRejectCiNetInquiryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public CustomerFinancialPositionServiceReference.operationResult approveOrRejectCiNetInquiryResult;
        
        public approveOrRejectCiNetInquiryResponse()
        {
        }
        
        public approveOrRejectCiNetInquiryResponse(CustomerFinancialPositionServiceReference.operationResult approveOrRejectCiNetInquiryResult)
        {
            this.approveOrRejectCiNetInquiryResult = approveOrRejectCiNetInquiryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerDuties", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getCustomerDutiesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string civilID;
        
        public getCustomerDutiesRequest()
        {
        }
        
        public getCustomerDutiesRequest(string civilID)
        {
            this.civilID = civilID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerDutiesResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getCustomerDutiesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public CustomerFinancialPositionServiceReference.financialPositionDTO getCustomerDutiesResult;
        
        public getCustomerDutiesResponse()
        {
        }
        
        public getCustomerDutiesResponse(CustomerFinancialPositionServiceReference.financialPositionDTO getCustomerDutiesResult)
        {
            this.getCustomerDutiesResult = getCustomerDutiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerCiNetCommercialDuties", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getCustomerCiNetCommercialDutiesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public CustomerFinancialPositionServiceReference.ciNetCommReportRequestVo ciNetCommercialReportRequest;
        
        public getCustomerCiNetCommercialDutiesRequest()
        {
        }
        
        public getCustomerCiNetCommercialDutiesRequest(CustomerFinancialPositionServiceReference.ciNetCommReportRequestVo ciNetCommercialReportRequest)
        {
            this.ciNetCommercialReportRequest = ciNetCommercialReportRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerCiNetCommercialDutiesResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getCustomerCiNetCommercialDutiesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public CustomerFinancialPositionServiceReference.customerCreditInformationReport getCustomerCiNetCommercialDutiesResult;
        
        public getCustomerCiNetCommercialDutiesResponse()
        {
        }
        
        public getCustomerCiNetCommercialDutiesResponse(CustomerFinancialPositionServiceReference.customerCreditInformationReport getCustomerCiNetCommercialDutiesResult)
        {
            this.getCustomerCiNetCommercialDutiesResult = getCustomerCiNetCommercialDutiesResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class ciNetLookup
    {
        
        private keyValuePair[] inquiryReasonField;
        
        private keyValuePair[] accountRelationshipField;
        
        private keyValuePair[] portifolioTypeField;
        
        private keyValuePair[] responseTypeField;
        
        private keyValuePair[] identifierTypeField;
        
        private keyValuePair[] accountTypeField;
        
        private keyValuePair[] paymentFrequencyField;
        
        private keyValuePair[] occupationField;
        
        private keyValuePair[] durationUnitField;
        
        private keyValuePair[] applicationStatusField;
        
        private keyValuePair[] purposeCodesField;
        
        private keyValuePair[] productTypeField;
        
        private keyValuePair[] accountSubTypeField;
        
        private keyValuePair[] residenceStatusField;
        
        private keyValuePair[] sectorCodeField;
        
        private keyValuePair[] legalCapacityField;
        
        private keyValuePair[] reasonForWriteoffField;
        
        private keyValuePair[] reasonForClosureField;
        
        private keyValuePair[] commercialAccountTypesField;
        
        private keyValuePair[] enterpriseSizeField;
        
        private keyValuePair[] collateralTypesField;
        
        private keyValuePair[] legalEntityTypeField;
        
        private keyValuePair[] natureOfCreditLimitField;
        
        private keyValuePair[] natureOfCollateralCoverageField;
        
        private keyValuePair[] purposeOfTheFacilityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] inquiryReason
        {
            get
            {
                return this.inquiryReasonField;
            }
            set
            {
                this.inquiryReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] accountRelationship
        {
            get
            {
                return this.accountRelationshipField;
            }
            set
            {
                this.accountRelationshipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] portifolioType
        {
            get
            {
                return this.portifolioTypeField;
            }
            set
            {
                this.portifolioTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] responseType
        {
            get
            {
                return this.responseTypeField;
            }
            set
            {
                this.responseTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] identifierType
        {
            get
            {
                return this.identifierTypeField;
            }
            set
            {
                this.identifierTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] accountType
        {
            get
            {
                return this.accountTypeField;
            }
            set
            {
                this.accountTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] paymentFrequency
        {
            get
            {
                return this.paymentFrequencyField;
            }
            set
            {
                this.paymentFrequencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] occupation
        {
            get
            {
                return this.occupationField;
            }
            set
            {
                this.occupationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] durationUnit
        {
            get
            {
                return this.durationUnitField;
            }
            set
            {
                this.durationUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] applicationStatus
        {
            get
            {
                return this.applicationStatusField;
            }
            set
            {
                this.applicationStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] purposeCodes
        {
            get
            {
                return this.purposeCodesField;
            }
            set
            {
                this.purposeCodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] productType
        {
            get
            {
                return this.productTypeField;
            }
            set
            {
                this.productTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] accountSubType
        {
            get
            {
                return this.accountSubTypeField;
            }
            set
            {
                this.accountSubTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] residenceStatus
        {
            get
            {
                return this.residenceStatusField;
            }
            set
            {
                this.residenceStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] sectorCode
        {
            get
            {
                return this.sectorCodeField;
            }
            set
            {
                this.sectorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] legalCapacity
        {
            get
            {
                return this.legalCapacityField;
            }
            set
            {
                this.legalCapacityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] reasonForWriteoff
        {
            get
            {
                return this.reasonForWriteoffField;
            }
            set
            {
                this.reasonForWriteoffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] reasonForClosure
        {
            get
            {
                return this.reasonForClosureField;
            }
            set
            {
                this.reasonForClosureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] commercialAccountTypes
        {
            get
            {
                return this.commercialAccountTypesField;
            }
            set
            {
                this.commercialAccountTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] enterpriseSize
        {
            get
            {
                return this.enterpriseSizeField;
            }
            set
            {
                this.enterpriseSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] collateralTypes
        {
            get
            {
                return this.collateralTypesField;
            }
            set
            {
                this.collateralTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] legalEntityType
        {
            get
            {
                return this.legalEntityTypeField;
            }
            set
            {
                this.legalEntityTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] natureOfCreditLimit
        {
            get
            {
                return this.natureOfCreditLimitField;
            }
            set
            {
                this.natureOfCreditLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] natureOfCollateralCoverage
        {
            get
            {
                return this.natureOfCollateralCoverageField;
            }
            set
            {
                this.natureOfCollateralCoverageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] purposeOfTheFacility
        {
            get
            {
                return this.purposeOfTheFacilityField;
            }
            set
            {
                this.purposeOfTheFacilityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class keyValuePair
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCiNetLookupData", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getCiNetLookupDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string lookupName;
        
        public getCiNetLookupDataRequest()
        {
        }
        
        public getCiNetLookupDataRequest(string lookupName)
        {
            this.lookupName = lookupName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCiNetLookupDataResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getCiNetLookupDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public CustomerFinancialPositionServiceReference.ciNetLookup getCiNetLookupDataResult;
        
        public getCiNetLookupDataResponse()
        {
        }
        
        public getCiNetLookupDataResponse(CustomerFinancialPositionServiceReference.ciNetLookup getCiNetLookupDataResult)
        {
            this.getCiNetLookupDataResult = getCiNetLookupDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface CustomerFinancialPositionServiceChannel : CustomerFinancialPositionServiceReference.CustomerFinancialPositionService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class CustomerFinancialPositionServiceClient : System.ServiceModel.ClientBase<CustomerFinancialPositionServiceReference.CustomerFinancialPositionService>, CustomerFinancialPositionServiceReference.CustomerFinancialPositionService
    {
        
        public CustomerFinancialPositionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<CustomerFinancialPositionServiceReference.getCustomerCiNetDutiesResponse> getCustomerCiNetDutiesAsync(CustomerFinancialPositionServiceReference.getCustomerCiNetDutiesRequest request)
        {
            return base.Channel.getCustomerCiNetDutiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CustomerFinancialPositionServiceReference.approveOrRejectCiNetInquiryResponse> approveOrRejectCiNetInquiryAsync(CustomerFinancialPositionServiceReference.approveOrRejectCiNetInquiryRequest request)
        {
            return base.Channel.approveOrRejectCiNetInquiryAsync(request);
        }
        
        public System.Threading.Tasks.Task<CustomerFinancialPositionServiceReference.getCustomerDutiesResponse> getCustomerDutiesAsync(CustomerFinancialPositionServiceReference.getCustomerDutiesRequest request)
        {
            return base.Channel.getCustomerDutiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CustomerFinancialPositionServiceReference.getCustomerCiNetCommercialDutiesResponse> getCustomerCiNetCommercialDutiesAsync(CustomerFinancialPositionServiceReference.getCustomerCiNetCommercialDutiesRequest request)
        {
            return base.Channel.getCustomerCiNetCommercialDutiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CustomerFinancialPositionServiceReference.getCiNetLookupDataResponse> getCiNetLookupDataAsync(CustomerFinancialPositionServiceReference.getCiNetLookupDataRequest request)
        {
            return base.Channel.getCiNetLookupDataAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
