//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountHoldMgmtServiceReference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class Exception
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class HoldDetails
    {
        
        private double amountField;
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.DateTime expiryDateField;
        
        private bool expiryDateFieldSpecified;
        
        private string descriptionField;
        
        private string instructionField;
        
        private string tracerField;
        
        private long holdIdField;
        
        private long employeeIdField;
        
        private bool employeeIdFieldSpecified;
        
        private string holdTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified
        {
            get
            {
                return this.startDateFieldSpecified;
            }
            set
            {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ExpiryDate
        {
            get
            {
                return this.expiryDateField;
            }
            set
            {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiryDateSpecified
        {
            get
            {
                return this.expiryDateFieldSpecified;
            }
            set
            {
                this.expiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Instruction
        {
            get
            {
                return this.instructionField;
            }
            set
            {
                this.instructionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Tracer
        {
            get
            {
                return this.tracerField;
            }
            set
            {
                this.tracerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long HoldId
        {
            get
            {
                return this.holdIdField;
            }
            set
            {
                this.holdIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long EmployeeId
        {
            get
            {
                return this.employeeIdField;
            }
            set
            {
                this.employeeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmployeeIdSpecified
        {
            get
            {
                return this.employeeIdFieldSpecified;
            }
            set
            {
                this.employeeIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string HoldType
        {
            get
            {
                return this.holdTypeField;
            }
            set
            {
                this.holdTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class holdsList
    {
        
        private double totalAmountField;
        
        private int numberOfHoldsField;
        
        private HoldDetails[] listOfHoldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double TotalAmount
        {
            get
            {
                return this.totalAmountField;
            }
            set
            {
                this.totalAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int NumberOfHolds
        {
            get
            {
                return this.numberOfHoldsField;
            }
            set
            {
                this.numberOfHoldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public HoldDetails[] listOfHolds
        {
            get
            {
                return this.listOfHoldsField;
            }
            set
            {
                this.listOfHoldsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.openuri.org/", ConfigurationName="AccountHoldMgmtServiceReference.AccountHoldMgmtService")]
    public interface AccountHoldMgmtService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/AccountHoldMgmtService/viewHoldsListRequest", ReplyAction="http://www.openuri.org/AccountHoldMgmtService/viewHoldsListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AccountHoldMgmtServiceReference.Exception), Action="http://www.openuri.org/AccountHoldMgmtService/viewHoldsList/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AccountHoldMgmtServiceReference.viewHoldsListResponse> viewHoldsListAsync(AccountHoldMgmtServiceReference.viewHoldsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/AccountHoldMgmtService/viewHoldDetailsRequest", ReplyAction="http://www.openuri.org/AccountHoldMgmtService/viewHoldDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AccountHoldMgmtServiceReference.Exception), Action="http://www.openuri.org/AccountHoldMgmtService/viewHoldDetails/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AccountHoldMgmtServiceReference.viewHoldDetailsResponse> viewHoldDetailsAsync(AccountHoldMgmtServiceReference.viewHoldDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/AccountHoldMgmtService/viewAllHoldDetailsRequest", ReplyAction="http://www.openuri.org/AccountHoldMgmtService/viewAllHoldDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AccountHoldMgmtServiceReference.Exception), Action="http://www.openuri.org/AccountHoldMgmtService/viewAllHoldDetails/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AccountHoldMgmtServiceReference.viewAllHoldDetailsResponse> viewAllHoldDetailsAsync(AccountHoldMgmtServiceReference.viewAllHoldDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/AccountHoldMgmtService/updateHoldDetailsRequest", ReplyAction="http://www.openuri.org/AccountHoldMgmtService/updateHoldDetailsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AccountHoldMgmtServiceReference.updateHoldDetailsResponse> updateHoldDetailsAsync(AccountHoldMgmtServiceReference.updateHoldDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/AccountHoldMgmtService/addHoldRequest", ReplyAction="http://www.openuri.org/AccountHoldMgmtService/addHoldResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AccountHoldMgmtServiceReference.Exception), Action="http://www.openuri.org/AccountHoldMgmtService/addHold/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AccountHoldMgmtServiceReference.addHoldResponse> addHoldAsync(AccountHoldMgmtServiceReference.addHoldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="viewHoldsList", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class viewHoldsListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string acct;
        
        public viewHoldsListRequest()
        {
        }
        
        public viewHoldsListRequest(string acct)
        {
            this.acct = acct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="viewHoldsListResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class viewHoldsListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public AccountHoldMgmtServiceReference.holdsList viewHoldsListResult;
        
        public viewHoldsListResponse()
        {
        }
        
        public viewHoldsListResponse(AccountHoldMgmtServiceReference.holdsList viewHoldsListResult)
        {
            this.viewHoldsListResult = viewHoldsListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="viewHoldDetails", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class viewHoldDetailsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string acct;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=1)]
        public int holdId;
        
        public viewHoldDetailsRequest()
        {
        }
        
        public viewHoldDetailsRequest(string acct, int holdId)
        {
            this.acct = acct;
            this.holdId = holdId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="viewHoldDetailsResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class viewHoldDetailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public AccountHoldMgmtServiceReference.HoldDetails viewHoldDetailsResult;
        
        public viewHoldDetailsResponse()
        {
        }
        
        public viewHoldDetailsResponse(AccountHoldMgmtServiceReference.HoldDetails viewHoldDetailsResult)
        {
            this.viewHoldDetailsResult = viewHoldDetailsResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class allHoldDetails
    {
        
        private double amountField;
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.DateTime expiryDateField;
        
        private bool expiryDateFieldSpecified;
        
        private string descriptionField;
        
        private string instructionField;
        
        private string tracerField;
        
        private long holdIdField;
        
        private string statusField;
        
        private string holdTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified
        {
            get
            {
                return this.startDateFieldSpecified;
            }
            set
            {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ExpiryDate
        {
            get
            {
                return this.expiryDateField;
            }
            set
            {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiryDateSpecified
        {
            get
            {
                return this.expiryDateFieldSpecified;
            }
            set
            {
                this.expiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Instruction
        {
            get
            {
                return this.instructionField;
            }
            set
            {
                this.instructionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Tracer
        {
            get
            {
                return this.tracerField;
            }
            set
            {
                this.tracerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long HoldId
        {
            get
            {
                return this.holdIdField;
            }
            set
            {
                this.holdIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string HoldType
        {
            get
            {
                return this.holdTypeField;
            }
            set
            {
                this.holdTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="viewAllHoldDetails", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class viewAllHoldDetailsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string acct;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=1)]
        public int holdId;
        
        public viewAllHoldDetailsRequest()
        {
        }
        
        public viewAllHoldDetailsRequest(string acct, int holdId)
        {
            this.acct = acct;
            this.holdId = holdId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="viewAllHoldDetailsResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class viewAllHoldDetailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public AccountHoldMgmtServiceReference.allHoldDetails viewAllHoldDetailsResult;
        
        public viewAllHoldDetailsResponse()
        {
        }
        
        public viewAllHoldDetailsResponse(AccountHoldMgmtServiceReference.allHoldDetails viewAllHoldDetailsResult)
        {
            this.viewAllHoldDetailsResult = viewAllHoldDetailsResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class updateHoldResult : result
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(updateHoldResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class result
    {
        
        private bool isSuccessfulField;
        
        private string errorCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool isSuccessful
        {
            get
            {
                return this.isSuccessfulField;
            }
            set
            {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateHoldDetails", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class updateHoldDetailsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string holdId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=1)]
        public string accountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=2)]
        public string amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=3)]
        public int userId;
        
        public updateHoldDetailsRequest()
        {
        }
        
        public updateHoldDetailsRequest(string holdId, string accountNumber, string amount, int userId)
        {
            this.holdId = holdId;
            this.accountNumber = accountNumber;
            this.amount = amount;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateHoldDetailsResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class updateHoldDetailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public AccountHoldMgmtServiceReference.updateHoldResult updateHoldDetailsResult;
        
        public updateHoldDetailsResponse()
        {
        }
        
        public updateHoldDetailsResponse(AccountHoldMgmtServiceReference.updateHoldResult updateHoldDetailsResult)
        {
            this.updateHoldDetailsResult = updateHoldDetailsResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class holdResult
    {
        
        private string referenceNoField;
        
        private double holdBalanceField;
        
        private double availableBalanceField;
        
        private double currentBalanceField;
        
        private int holdIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ReferenceNo
        {
            get
            {
                return this.referenceNoField;
            }
            set
            {
                this.referenceNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double HoldBalance
        {
            get
            {
                return this.holdBalanceField;
            }
            set
            {
                this.holdBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double AvailableBalance
        {
            get
            {
                return this.availableBalanceField;
            }
            set
            {
                this.availableBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double CurrentBalance
        {
            get
            {
                return this.currentBalanceField;
            }
            set
            {
                this.currentBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int HoldId
        {
            get
            {
                return this.holdIdField;
            }
            set
            {
                this.holdIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addHold", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class addHoldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string acctNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=1)]
        public double amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=2)]
        public System.DateTime holdExpiryDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=3)]
        public int holdNoOfDays;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=4)]
        public string instructions;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=5)]
        public string description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=6)]
        public int userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=7)]
        public string holdType;
        
        public addHoldRequest()
        {
        }
        
        public addHoldRequest(string acctNo, double amount, System.DateTime holdExpiryDate, int holdNoOfDays, string instructions, string description, int userId, string holdType)
        {
            this.acctNo = acctNo;
            this.amount = amount;
            this.holdExpiryDate = holdExpiryDate;
            this.holdNoOfDays = holdNoOfDays;
            this.instructions = instructions;
            this.description = description;
            this.userId = userId;
            this.holdType = holdType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addHoldResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class addHoldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public AccountHoldMgmtServiceReference.holdResult addHoldResult;
        
        public addHoldResponse()
        {
        }
        
        public addHoldResponse(AccountHoldMgmtServiceReference.holdResult addHoldResult)
        {
            this.addHoldResult = addHoldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface AccountHoldMgmtServiceChannel : AccountHoldMgmtServiceReference.AccountHoldMgmtService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class AccountHoldMgmtServiceClient : System.ServiceModel.ClientBase<AccountHoldMgmtServiceReference.AccountHoldMgmtService>, AccountHoldMgmtServiceReference.AccountHoldMgmtService
    {
        
        public AccountHoldMgmtServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AccountHoldMgmtServiceReference.viewHoldsListResponse> viewHoldsListAsync(AccountHoldMgmtServiceReference.viewHoldsListRequest request)
        {
            return base.Channel.viewHoldsListAsync(request);
        }
        
        public System.Threading.Tasks.Task<AccountHoldMgmtServiceReference.viewHoldDetailsResponse> viewHoldDetailsAsync(AccountHoldMgmtServiceReference.viewHoldDetailsRequest request)
        {
            return base.Channel.viewHoldDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AccountHoldMgmtServiceReference.viewAllHoldDetailsResponse> viewAllHoldDetailsAsync(AccountHoldMgmtServiceReference.viewAllHoldDetailsRequest request)
        {
            return base.Channel.viewAllHoldDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AccountHoldMgmtServiceReference.updateHoldDetailsResponse> updateHoldDetailsAsync(AccountHoldMgmtServiceReference.updateHoldDetailsRequest request)
        {
            return base.Channel.updateHoldDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AccountHoldMgmtServiceReference.addHoldResponse> addHoldAsync(AccountHoldMgmtServiceReference.addHoldRequest request)
        {
            return base.Channel.addHoldAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
