//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrServiceReference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class Exception
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.openuri.org/", ConfigurationName="HrServiceReference.HrService")]
    public interface HrService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/HrService/getEmployeeNoRequest", ReplyAction="http://www.openuri.org/HrService/getEmployeeNoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HrServiceReference.Exception), Action="http://www.openuri.org/HrService/getEmployeeNo/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HrServiceReference.getEmployeeNoResponse> getEmployeeNoAsync(HrServiceReference.getEmployeeNoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/HrService/getEmployeeInfoRequest", ReplyAction="http://www.openuri.org/HrService/getEmployeeInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HrServiceReference.Exception), Action="http://www.openuri.org/HrService/getEmployeeInfo/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HrServiceReference.getEmployeeInfoResponse> getEmployeeInfoAsync(HrServiceReference.getEmployeeInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/HrService/getSalaryMonthsRequest", ReplyAction="http://www.openuri.org/HrService/getSalaryMonthsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HrServiceReference.Exception), Action="http://www.openuri.org/HrService/getSalaryMonths/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HrServiceReference.getSalaryMonthsResponse> getSalaryMonthsAsync(HrServiceReference.getSalaryMonthsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/HrService/getEmployeeNoByAcctRequest", ReplyAction="http://www.openuri.org/HrService/getEmployeeNoByAcctResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HrServiceReference.Exception), Action="http://www.openuri.org/HrService/getEmployeeNoByAcct/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HrServiceReference.getEmployeeNoByAcctResponse> getEmployeeNoByAcctAsync(HrServiceReference.getEmployeeNoByAcctRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/HrService/getEmployeeSalaryDetailRequest", ReplyAction="http://www.openuri.org/HrService/getEmployeeSalaryDetailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HrServiceReference.Exception), Action="http://www.openuri.org/HrService/getEmployeeSalaryDetail/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HrServiceReference.getEmployeeSalaryDetailResponse> getEmployeeSalaryDetailAsync(HrServiceReference.getEmployeeSalaryDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/HrService/getEmployeeLoanDetailRequest", ReplyAction="http://www.openuri.org/HrService/getEmployeeLoanDetailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HrServiceReference.Exception), Action="http://www.openuri.org/HrService/getEmployeeLoanDetail/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HrServiceReference.getEmployeeLoanDetailResponse> getEmployeeLoanDetailAsync(HrServiceReference.getEmployeeLoanDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/HrService/getEmployeeLeavesRequest", ReplyAction="http://www.openuri.org/HrService/getEmployeeLeavesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HrServiceReference.Exception), Action="http://www.openuri.org/HrService/getEmployeeLeaves/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HrServiceReference.getEmployeeLeavesResponse> getEmployeeLeavesAsync(HrServiceReference.getEmployeeLeavesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEmployeeNo", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getEmployeeNoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] acctList;
        
        public getEmployeeNoRequest()
        {
        }
        
        public getEmployeeNoRequest(string[] acctList)
        {
            this.acctList = acctList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEmployeeNoResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getEmployeeNoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string getEmployeeNoResult;
        
        public getEmployeeNoResponse()
        {
        }
        
        public getEmployeeNoResponse(string getEmployeeNoResult)
        {
            this.getEmployeeNoResult = getEmployeeNoResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class employeeInfo
    {
        
        private string empNoField;
        
        private string nameField;
        
        private System.DateTime hireDateField;
        
        private bool hireDateFieldSpecified;
        
        private string nationalityField;
        
        private string nationalityNoField;
        
        private string passportNoField;
        
        private System.DateTime passportEndDateField;
        
        private bool passportEndDateFieldSpecified;
        
        private System.DateTime residenceEndDateField;
        
        private bool residenceEndDateFieldSpecified;
        
        private string civilIDField;
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private string acctNoField;
        
        private string maritalStatusField;
        
        private string genderField;
        
        private string qualificationField;
        
        private string gradeField;
        
        private string positionField;
        
        private string organizationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string empNo
        {
            get
            {
                return this.empNoField;
            }
            set
            {
                this.empNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime hireDate
        {
            get
            {
                return this.hireDateField;
            }
            set
            {
                this.hireDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hireDateSpecified
        {
            get
            {
                return this.hireDateFieldSpecified;
            }
            set
            {
                this.hireDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string nationality
        {
            get
            {
                return this.nationalityField;
            }
            set
            {
                this.nationalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string nationalityNo
        {
            get
            {
                return this.nationalityNoField;
            }
            set
            {
                this.nationalityNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string passportNo
        {
            get
            {
                return this.passportNoField;
            }
            set
            {
                this.passportNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime passportEndDate
        {
            get
            {
                return this.passportEndDateField;
            }
            set
            {
                this.passportEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool passportEndDateSpecified
        {
            get
            {
                return this.passportEndDateFieldSpecified;
            }
            set
            {
                this.passportEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime residenceEndDate
        {
            get
            {
                return this.residenceEndDateField;
            }
            set
            {
                this.residenceEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool residenceEndDateSpecified
        {
            get
            {
                return this.residenceEndDateFieldSpecified;
            }
            set
            {
                this.residenceEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string civilID
        {
            get
            {
                return this.civilIDField;
            }
            set
            {
                this.civilIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime birthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthDateSpecified
        {
            get
            {
                return this.birthDateFieldSpecified;
            }
            set
            {
                this.birthDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string acctNo
        {
            get
            {
                return this.acctNoField;
            }
            set
            {
                this.acctNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string maritalStatus
        {
            get
            {
                return this.maritalStatusField;
            }
            set
            {
                this.maritalStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string qualification
        {
            get
            {
                return this.qualificationField;
            }
            set
            {
                this.qualificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string organization
        {
            get
            {
                return this.organizationField;
            }
            set
            {
                this.organizationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEmployeeInfo", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getEmployeeInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string empNo;
        
        public getEmployeeInfoRequest()
        {
        }
        
        public getEmployeeInfoRequest(string empNo)
        {
            this.empNo = empNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEmployeeInfoResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getEmployeeInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public HrServiceReference.employeeInfo getEmployeeInfoResult;
        
        public getEmployeeInfoResponse()
        {
        }
        
        public getEmployeeInfoResponse(HrServiceReference.employeeInfo getEmployeeInfoResult)
        {
            this.getEmployeeInfoResult = getEmployeeInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSalaryMonths", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getSalaryMonthsRequest
    {
        
        public getSalaryMonthsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSalaryMonthsResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getSalaryMonthsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getSalaryMonthsResponse()
        {
        }
        
        public getSalaryMonthsResponse(string[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEmployeeNoByAcct", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getEmployeeNoByAcctRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string acctNo;
        
        public getEmployeeNoByAcctRequest()
        {
        }
        
        public getEmployeeNoByAcctRequest(string acctNo)
        {
            this.acctNo = acctNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEmployeeNoByAcctResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getEmployeeNoByAcctResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string getEmployeeNoByAcctResult;
        
        public getEmployeeNoByAcctResponse()
        {
        }
        
        public getEmployeeNoByAcctResponse(string getEmployeeNoByAcctResult)
        {
            this.getEmployeeNoByAcctResult = getEmployeeNoByAcctResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class salaryDetail
    {
        
        private double netSalaryField;
        
        private salaryElement[] salaryElementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double netSalary
        {
            get
            {
                return this.netSalaryField;
            }
            set
            {
                this.netSalaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SalaryElement", IsNullable=false)]
        public salaryElement[] salaryElements
        {
            get
            {
                return this.salaryElementsField;
            }
            set
            {
                this.salaryElementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class salaryElement
    {
        
        private string salaryElementNameField;
        
        private double salaryElementValueField;
        
        private string salaryElementTypeField;
        
        private string salaryElementRemarkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string salaryElementName
        {
            get
            {
                return this.salaryElementNameField;
            }
            set
            {
                this.salaryElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double salaryElementValue
        {
            get
            {
                return this.salaryElementValueField;
            }
            set
            {
                this.salaryElementValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string salaryElementType
        {
            get
            {
                return this.salaryElementTypeField;
            }
            set
            {
                this.salaryElementTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string salaryElementRemark
        {
            get
            {
                return this.salaryElementRemarkField;
            }
            set
            {
                this.salaryElementRemarkField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEmployeeSalaryDetail", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getEmployeeSalaryDetailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string empNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=1)]
        public string salaryDate;
        
        public getEmployeeSalaryDetailRequest()
        {
        }
        
        public getEmployeeSalaryDetailRequest(string empNo, string salaryDate)
        {
            this.empNo = empNo;
            this.salaryDate = salaryDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEmployeeSalaryDetailResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getEmployeeSalaryDetailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public HrServiceReference.salaryDetail getEmployeeSalaryDetailResult;
        
        public getEmployeeSalaryDetailResponse()
        {
        }
        
        public getEmployeeSalaryDetailResponse(HrServiceReference.salaryDetail getEmployeeSalaryDetailResult)
        {
            this.getEmployeeSalaryDetailResult = getEmployeeSalaryDetailResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class loanDetail
    {
        
        private double loanAmountField;
        
        private double instAmountField;
        
        private System.DateTime loanStartDateField;
        
        private bool loanStartDateFieldSpecified;
        
        private int totalDeductionsField;
        
        private double paidAmountField;
        
        private double remainingAmountField;
        
        private System.DateTime loanEndDateField;
        
        private bool loanEndDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double loanAmount
        {
            get
            {
                return this.loanAmountField;
            }
            set
            {
                this.loanAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double instAmount
        {
            get
            {
                return this.instAmountField;
            }
            set
            {
                this.instAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime loanStartDate
        {
            get
            {
                return this.loanStartDateField;
            }
            set
            {
                this.loanStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool loanStartDateSpecified
        {
            get
            {
                return this.loanStartDateFieldSpecified;
            }
            set
            {
                this.loanStartDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int totalDeductions
        {
            get
            {
                return this.totalDeductionsField;
            }
            set
            {
                this.totalDeductionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double paidAmount
        {
            get
            {
                return this.paidAmountField;
            }
            set
            {
                this.paidAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double remainingAmount
        {
            get
            {
                return this.remainingAmountField;
            }
            set
            {
                this.remainingAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime loanEndDate
        {
            get
            {
                return this.loanEndDateField;
            }
            set
            {
                this.loanEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool loanEndDateSpecified
        {
            get
            {
                return this.loanEndDateFieldSpecified;
            }
            set
            {
                this.loanEndDateFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEmployeeLoanDetail", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getEmployeeLoanDetailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string empNo;
        
        public getEmployeeLoanDetailRequest()
        {
        }
        
        public getEmployeeLoanDetailRequest(string empNo)
        {
            this.empNo = empNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEmployeeLoanDetailResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getEmployeeLoanDetailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LoanDetail")]
        public HrServiceReference.loanDetail[] getEmployeeLoanDetailResult;
        
        public getEmployeeLoanDetailResponse()
        {
        }
        
        public getEmployeeLoanDetailResponse(HrServiceReference.loanDetail[] getEmployeeLoanDetailResult)
        {
            this.getEmployeeLoanDetailResult = getEmployeeLoanDetailResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class employeeLeave
    {
        
        private string xsiTypeField;
        
        private double deservedField;
        
        private double currentField;
        
        private double accumulatedField;
        
        private double emergencyField;
        
        private double sickField;
        
        private leaveHistory[] leaveHistoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string xsiType
        {
            get
            {
                return this.xsiTypeField;
            }
            set
            {
                this.xsiTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double deserved
        {
            get
            {
                return this.deservedField;
            }
            set
            {
                this.deservedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double current
        {
            get
            {
                return this.currentField;
            }
            set
            {
                this.currentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double accumulated
        {
            get
            {
                return this.accumulatedField;
            }
            set
            {
                this.accumulatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double emergency
        {
            get
            {
                return this.emergencyField;
            }
            set
            {
                this.emergencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double sick
        {
            get
            {
                return this.sickField;
            }
            set
            {
                this.sickField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public leaveHistory[] leaveHistory
        {
            get
            {
                return this.leaveHistoryField;
            }
            set
            {
                this.leaveHistoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class leaveHistory
    {
        
        private System.DateTime fromDateField;
        
        private bool fromDateFieldSpecified;
        
        private System.DateTime toDateField;
        
        private bool toDateFieldSpecified;
        
        private string leaveDescriptionField;
        
        private int numberOfDaysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime fromDate
        {
            get
            {
                return this.fromDateField;
            }
            set
            {
                this.fromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fromDateSpecified
        {
            get
            {
                return this.fromDateFieldSpecified;
            }
            set
            {
                this.fromDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime toDate
        {
            get
            {
                return this.toDateField;
            }
            set
            {
                this.toDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool toDateSpecified
        {
            get
            {
                return this.toDateFieldSpecified;
            }
            set
            {
                this.toDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string leaveDescription
        {
            get
            {
                return this.leaveDescriptionField;
            }
            set
            {
                this.leaveDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int numberOfDays
        {
            get
            {
                return this.numberOfDaysField;
            }
            set
            {
                this.numberOfDaysField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEmployeeLeaves", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getEmployeeLeavesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string empNo;
        
        public getEmployeeLeavesRequest()
        {
        }
        
        public getEmployeeLeavesRequest(string empNo)
        {
            this.empNo = empNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEmployeeLeavesResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getEmployeeLeavesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public HrServiceReference.employeeLeave getEmployeeLeavesResult;
        
        public getEmployeeLeavesResponse()
        {
        }
        
        public getEmployeeLeavesResponse(HrServiceReference.employeeLeave getEmployeeLeavesResult)
        {
            this.getEmployeeLeavesResult = getEmployeeLeavesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface HrServiceChannel : HrServiceReference.HrService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class HrServiceClient : System.ServiceModel.ClientBase<HrServiceReference.HrService>, HrServiceReference.HrService
    {
        
        public HrServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<HrServiceReference.getEmployeeNoResponse> getEmployeeNoAsync(HrServiceReference.getEmployeeNoRequest request)
        {
            return base.Channel.getEmployeeNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<HrServiceReference.getEmployeeInfoResponse> getEmployeeInfoAsync(HrServiceReference.getEmployeeInfoRequest request)
        {
            return base.Channel.getEmployeeInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<HrServiceReference.getSalaryMonthsResponse> getSalaryMonthsAsync(HrServiceReference.getSalaryMonthsRequest request)
        {
            return base.Channel.getSalaryMonthsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HrServiceReference.getEmployeeNoByAcctResponse> getEmployeeNoByAcctAsync(HrServiceReference.getEmployeeNoByAcctRequest request)
        {
            return base.Channel.getEmployeeNoByAcctAsync(request);
        }
        
        public System.Threading.Tasks.Task<HrServiceReference.getEmployeeSalaryDetailResponse> getEmployeeSalaryDetailAsync(HrServiceReference.getEmployeeSalaryDetailRequest request)
        {
            return base.Channel.getEmployeeSalaryDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<HrServiceReference.getEmployeeLoanDetailResponse> getEmployeeLoanDetailAsync(HrServiceReference.getEmployeeLoanDetailRequest request)
        {
            return base.Channel.getEmployeeLoanDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<HrServiceReference.getEmployeeLeavesResponse> getEmployeeLeavesAsync(HrServiceReference.getEmployeeLeavesRequest request)
        {
            return base.Channel.getEmployeeLeavesAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
