//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceFeesManagementReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.kfh.com/", ConfigurationName="ServiceFeesManagementReference.ServiceFeesManagement")]
    public interface ServiceFeesManagement
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kfh.com/ServiceFeesManagement/getServiceFeesRequest", ReplyAction="http://www.kfh.com/ServiceFeesManagement/getServiceFeesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceFeesManagementReference.getServiceFeesResponse> getServiceFeesAsync(ServiceFeesManagementReference.getServiceFeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kfh.com/ServiceFeesManagement/postServiceFeesRequest", ReplyAction="http://www.kfh.com/ServiceFeesManagement/postServiceFeesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceFeesManagementReference.postServiceFeesResponse> postServiceFeesAsync(ServiceFeesManagementReference.postServiceFeesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kfh.com/")]
    public partial class getServiceFeesReqDTO
    {
        
        private string glCurrencyField;
        
        private string serviceAccountNoField;
        
        private string serviceNameField;
        
        private int tranTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string glCurrency
        {
            get
            {
                return this.glCurrencyField;
            }
            set
            {
                this.glCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string serviceAccountNo
        {
            get
            {
                return this.serviceAccountNoField;
            }
            set
            {
                this.serviceAccountNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string serviceName
        {
            get
            {
                return this.serviceNameField;
            }
            set
            {
                this.serviceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int tranType
        {
            get
            {
                return this.tranTypeField;
            }
            set
            {
                this.tranTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kfh.com/")]
    public partial class transactionPostResutDTO
    {
        
        private string errorCodeField;
        
        private string errorDescField;
        
        private bool isSuccessfulField;
        
        private string transRefnoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorDesc
        {
            get
            {
                return this.errorDescField;
            }
            set
            {
                this.errorDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool isSuccessful
        {
            get
            {
                return this.isSuccessfulField;
            }
            set
            {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string transRefno
        {
            get
            {
                return this.transRefnoField;
            }
            set
            {
                this.transRefnoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kfh.com/")]
    public partial class keyValuePair
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kfh.com/")]
    public partial class postServiceFeesReqDTO
    {
        
        private double currencyRateField;
        
        private bool currencyRateFieldSpecified;
        
        private keyValuePair[] dataAttributeListField;
        
        private string debitAccountNoField;
        
        private string glCurrencyField;
        
        private double originalFeesAmountField;
        
        private bool originalFeesAmountFieldSpecified;
        
        private double overwriteFeesAmountField;
        
        private bool overwriteFeesAmountFieldSpecified;
        
        private string overwriteReasonField;
        
        private string serviceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double currencyRate
        {
            get
            {
                return this.currencyRateField;
            }
            set
            {
                this.currencyRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currencyRateSpecified
        {
            get
            {
                return this.currencyRateFieldSpecified;
            }
            set
            {
                this.currencyRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public keyValuePair[] dataAttributeList
        {
            get
            {
                return this.dataAttributeListField;
            }
            set
            {
                this.dataAttributeListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string debitAccountNo
        {
            get
            {
                return this.debitAccountNoField;
            }
            set
            {
                this.debitAccountNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string glCurrency
        {
            get
            {
                return this.glCurrencyField;
            }
            set
            {
                this.glCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double originalFeesAmount
        {
            get
            {
                return this.originalFeesAmountField;
            }
            set
            {
                this.originalFeesAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool originalFeesAmountSpecified
        {
            get
            {
                return this.originalFeesAmountFieldSpecified;
            }
            set
            {
                this.originalFeesAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double overwriteFeesAmount
        {
            get
            {
                return this.overwriteFeesAmountField;
            }
            set
            {
                this.overwriteFeesAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool overwriteFeesAmountSpecified
        {
            get
            {
                return this.overwriteFeesAmountFieldSpecified;
            }
            set
            {
                this.overwriteFeesAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string overwriteReason
        {
            get
            {
                return this.overwriteReasonField;
            }
            set
            {
                this.overwriteReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string serviceName
        {
            get
            {
                return this.serviceNameField;
            }
            set
            {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kfh.com/")]
    public partial class getServiceFeesResutDTO
    {
        
        private string errorCodeField;
        
        private string errorDescField;
        
        private double feesField;
        
        private string feesCurrencyField;
        
        private string feesValueTypeField;
        
        private string incomeGLField;
        
        private bool isVatApplicableField;
        
        private string taxGLField;
        
        private double vatPercentageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorDesc
        {
            get
            {
                return this.errorDescField;
            }
            set
            {
                this.errorDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double fees
        {
            get
            {
                return this.feesField;
            }
            set
            {
                this.feesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string feesCurrency
        {
            get
            {
                return this.feesCurrencyField;
            }
            set
            {
                this.feesCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string feesValueType
        {
            get
            {
                return this.feesValueTypeField;
            }
            set
            {
                this.feesValueTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string incomeGL
        {
            get
            {
                return this.incomeGLField;
            }
            set
            {
                this.incomeGLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool isVatApplicable
        {
            get
            {
                return this.isVatApplicableField;
            }
            set
            {
                this.isVatApplicableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string taxGL
        {
            get
            {
                return this.taxGLField;
            }
            set
            {
                this.taxGLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double vatPercentage
        {
            get
            {
                return this.vatPercentageField;
            }
            set
            {
                this.vatPercentageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getServiceFees", WrapperNamespace="http://www.kfh.com/", IsWrapped=true)]
    public partial class getServiceFeesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kfh.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceFeesManagementReference.getServiceFeesReqDTO getServiceFeesReqDTO;
        
        public getServiceFeesRequest()
        {
        }
        
        public getServiceFeesRequest(ServiceFeesManagementReference.getServiceFeesReqDTO getServiceFeesReqDTO)
        {
            this.getServiceFeesReqDTO = getServiceFeesReqDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getServiceFeesResponse", WrapperNamespace="http://www.kfh.com/", IsWrapped=true)]
    public partial class getServiceFeesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kfh.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceFeesManagementReference.getServiceFeesResutDTO getServiceFees;
        
        public getServiceFeesResponse()
        {
        }
        
        public getServiceFeesResponse(ServiceFeesManagementReference.getServiceFeesResutDTO getServiceFees)
        {
            this.getServiceFees = getServiceFees;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="postServiceFees", WrapperNamespace="http://www.kfh.com/", IsWrapped=true)]
    public partial class postServiceFeesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kfh.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceFeesManagementReference.postServiceFeesReqDTO postServiceFeeReqDTO;
        
        public postServiceFeesRequest()
        {
        }
        
        public postServiceFeesRequest(ServiceFeesManagementReference.postServiceFeesReqDTO postServiceFeeReqDTO)
        {
            this.postServiceFeeReqDTO = postServiceFeeReqDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="postServiceFeesResponse", WrapperNamespace="http://www.kfh.com/", IsWrapped=true)]
    public partial class postServiceFeesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kfh.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceFeesManagementReference.transactionPostResutDTO postServiceFees;
        
        public postServiceFeesResponse()
        {
        }
        
        public postServiceFeesResponse(ServiceFeesManagementReference.transactionPostResutDTO postServiceFees)
        {
            this.postServiceFees = postServiceFees;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ServiceFeesManagementChannel : ServiceFeesManagementReference.ServiceFeesManagement, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServiceFeesManagementClient : System.ServiceModel.ClientBase<ServiceFeesManagementReference.ServiceFeesManagement>, ServiceFeesManagementReference.ServiceFeesManagement
    {
        
        public ServiceFeesManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceFeesManagementReference.getServiceFeesResponse> getServiceFeesAsync(ServiceFeesManagementReference.getServiceFeesRequest request)
        {
            return base.Channel.getServiceFeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceFeesManagementReference.postServiceFeesResponse> postServiceFeesAsync(ServiceFeesManagementReference.postServiceFeesRequest request)
        {
            return base.Channel.postServiceFeesAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
