//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddCreditCardStandingOrderServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.openuri.org/", ConfigurationName="AddCreditCardStandingOrderServiceReference.AddCreditCardStandingOrder")]
    public interface AddCreditCardStandingOrder
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/AddCreditCardStandingOrder/addCreditCardStandingOrderReque" +
            "st", ReplyAction="http://www.openuri.org/AddCreditCardStandingOrder/addCreditCardStandingOrderRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AddCreditCardStandingOrderServiceReference.addCreditCardStandingOrderResponse> addCreditCardStandingOrderAsync(AddCreditCardStandingOrderServiceReference.addCreditCardStandingOrderRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class creditCardResultDTO : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool isSuccessfulField;
        
        private string statusField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool isSuccessful
        {
            get
            {
                return this.isSuccessfulField;
            }
            set
            {
                this.isSuccessfulField = value;
                this.RaisePropertyChanged("isSuccessful");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addCreditCardStandingOrder", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class addCreditCardStandingOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public double amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=1)]
        public string cardNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=2)]
        public string chargeAccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=3)]
        public int numberOfTransfer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=4)]
        public string debitAccountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=5)]
        public string startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=6)]
        public string endDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=7)]
        public int brNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TranSequence;
        
        public addCreditCardStandingOrderRequest()
        {
        }
        
        public addCreditCardStandingOrderRequest(double amount, string cardNo, string chargeAccount, int numberOfTransfer, string debitAccountNumber, string startDate, string endDate, int brNo, string TranSequence)
        {
            this.amount = amount;
            this.cardNo = cardNo;
            this.chargeAccount = chargeAccount;
            this.numberOfTransfer = numberOfTransfer;
            this.debitAccountNumber = debitAccountNumber;
            this.startDate = startDate;
            this.endDate = endDate;
            this.brNo = brNo;
            this.TranSequence = TranSequence;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addCreditCardStandingOrderResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class addCreditCardStandingOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public AddCreditCardStandingOrderServiceReference.creditCardResultDTO addCreditCardStandingOrderResult;
        
        public addCreditCardStandingOrderResponse()
        {
        }
        
        public addCreditCardStandingOrderResponse(AddCreditCardStandingOrderServiceReference.creditCardResultDTO addCreditCardStandingOrderResult)
        {
            this.addCreditCardStandingOrderResult = addCreditCardStandingOrderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface AddCreditCardStandingOrderChannel : AddCreditCardStandingOrderServiceReference.AddCreditCardStandingOrder, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class AddCreditCardStandingOrderClient : System.ServiceModel.ClientBase<AddCreditCardStandingOrderServiceReference.AddCreditCardStandingOrder>, AddCreditCardStandingOrderServiceReference.AddCreditCardStandingOrder
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AddCreditCardStandingOrderClient(EndpointConfiguration endpointConfiguration) : 
                base(AddCreditCardStandingOrderClient.GetBindingForEndpoint(endpointConfiguration), AddCreditCardStandingOrderClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AddCreditCardStandingOrderClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AddCreditCardStandingOrderClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AddCreditCardStandingOrderClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AddCreditCardStandingOrderClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AddCreditCardStandingOrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AddCreditCardStandingOrderServiceReference.addCreditCardStandingOrderResponse> addCreditCardStandingOrderAsync(AddCreditCardStandingOrderServiceReference.addCreditCardStandingOrderRequest request)
        {
            return base.Channel.addCreditCardStandingOrderAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap9))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap10))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap7))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap8))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap5))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap6))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap3))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap12))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap4))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap2))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap9))
            {
                return new System.ServiceModel.EndpointAddress("http://fzvdsoaap05:6655/kfhsoa/ws/AddCreditCardStandingOrder/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap10))
            {
                return new System.ServiceModel.EndpointAddress("http://fzvdsoaap05:6666/kfhsoa/ws/AddCreditCardStandingOrder/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap11))
            {
                return new System.ServiceModel.EndpointAddress("https://integration/kfhsoa/ws/AddCreditCardStandingOrder/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap7))
            {
                return new System.ServiceModel.EndpointAddress("https://soa_apigw/ws/WLS_AddCreditCardStandingOrder.AddCreditCardStandingOrderSoa" +
                        "p/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap8))
            {
                return new System.ServiceModel.EndpointAddress("https://soa_apigw/ws/WLS_AddCreditCardStandingOrder/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap5))
            {
                return new System.ServiceModel.EndpointAddress("https://integration/ws/WLS_AddCreditCardStandingOrder.AddCreditCardStandingOrderS" +
                        "oap/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap6))
            {
                return new System.ServiceModel.EndpointAddress("https://integration/ws/WLS_AddCreditCardStandingOrder/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://fzvdsoaap05:6655/ws/WLS_AddCreditCardStandingOrder.AddCreditCardStandingOr" +
                        "derSoap/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap3))
            {
                return new System.ServiceModel.EndpointAddress("http://fzvdsoaap05:6666/ws/WLS_AddCreditCardStandingOrder.AddCreditCardStandingOr" +
                        "derSoap/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://soa_apigw/kfhsoa/ws/AddCreditCardStandingOrder/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap4))
            {
                return new System.ServiceModel.EndpointAddress("http://fzvdsoaap05:6666/ws/WLS_AddCreditCardStandingOrder/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.AddCreditCardStandingOrderSoap2))
            {
                return new System.ServiceModel.EndpointAddress("http://fzvdsoaap05:6655/ws/WLS_AddCreditCardStandingOrder/1.0");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            AddCreditCardStandingOrderSoap9,
            
            AddCreditCardStandingOrderSoap10,
            
            AddCreditCardStandingOrderSoap11,
            
            AddCreditCardStandingOrderSoap7,
            
            AddCreditCardStandingOrderSoap8,
            
            AddCreditCardStandingOrderSoap5,
            
            AddCreditCardStandingOrderSoap6,
            
            AddCreditCardStandingOrderSoap,
            
            AddCreditCardStandingOrderSoap3,
            
            AddCreditCardStandingOrderSoap12,
            
            AddCreditCardStandingOrderSoap4,
            
            AddCreditCardStandingOrderSoap2,
        }
    }
}
