//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditCreditCardStandingOrderServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="creditCardResultDTO", Namespace="http://www.openuri.org/")]
    public partial class creditCardResultDTO : object
    {
        
        private bool isSuccessfulField;
        
        private string statusField;
        
        private string descriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool isSuccessful
        {
            get
            {
                return this.isSuccessfulField;
            }
            set
            {
                this.isSuccessfulField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.openuri.org/", ConfigurationName="EditCreditCardStandingOrderServiceReference.EditCreditCardStandingOrder")]
    public interface EditCreditCardStandingOrder
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/EditCreditCardStandingOrder/editCreditCardStandingOrderReq" +
            "uest", ReplyAction="http://www.openuri.org/EditCreditCardStandingOrder/editCreditCardStandingOrderRes" +
            "ponse")]
        System.Threading.Tasks.Task<EditCreditCardStandingOrderServiceReference.editCreditCardStandingOrderResponse> editCreditCardStandingOrderAsync(EditCreditCardStandingOrderServiceReference.editCreditCardStandingOrderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editCreditCardStandingOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editCreditCardStandingOrder", Namespace="http://www.openuri.org/", Order=0)]
        public EditCreditCardStandingOrderServiceReference.editCreditCardStandingOrderRequestBody Body;
        
        public editCreditCardStandingOrderRequest()
        {
        }
        
        public editCreditCardStandingOrderRequest(EditCreditCardStandingOrderServiceReference.editCreditCardStandingOrderRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.openuri.org/")]
    public partial class editCreditCardStandingOrderRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string debitAccountNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cardNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string chargeAccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int numberOfTransfer;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int soID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string startDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string endDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int brNo;
        
        public editCreditCardStandingOrderRequestBody()
        {
        }
        
        public editCreditCardStandingOrderRequestBody(string debitAccountNumber, double amount, string cardNo, string chargeAccount, int numberOfTransfer, int soID, string startDate, string endDate, int brNo)
        {
            this.debitAccountNumber = debitAccountNumber;
            this.amount = amount;
            this.cardNo = cardNo;
            this.chargeAccount = chargeAccount;
            this.numberOfTransfer = numberOfTransfer;
            this.soID = soID;
            this.startDate = startDate;
            this.endDate = endDate;
            this.brNo = brNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editCreditCardStandingOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editCreditCardStandingOrderResponse", Namespace="http://www.openuri.org/", Order=0)]
        public EditCreditCardStandingOrderServiceReference.editCreditCardStandingOrderResponseBody Body;
        
        public editCreditCardStandingOrderResponse()
        {
        }
        
        public editCreditCardStandingOrderResponse(EditCreditCardStandingOrderServiceReference.editCreditCardStandingOrderResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.openuri.org/")]
    public partial class editCreditCardStandingOrderResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EditCreditCardStandingOrderServiceReference.creditCardResultDTO editCreditCardStandingOrderResult;
        
        public editCreditCardStandingOrderResponseBody()
        {
        }
        
        public editCreditCardStandingOrderResponseBody(EditCreditCardStandingOrderServiceReference.creditCardResultDTO editCreditCardStandingOrderResult)
        {
            this.editCreditCardStandingOrderResult = editCreditCardStandingOrderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface EditCreditCardStandingOrderChannel : EditCreditCardStandingOrderServiceReference.EditCreditCardStandingOrder, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class EditCreditCardStandingOrderClient : System.ServiceModel.ClientBase<EditCreditCardStandingOrderServiceReference.EditCreditCardStandingOrder>, EditCreditCardStandingOrderServiceReference.EditCreditCardStandingOrder
    {
        
        public EditCreditCardStandingOrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<EditCreditCardStandingOrderServiceReference.editCreditCardStandingOrderResponse> editCreditCardStandingOrderAsync(EditCreditCardStandingOrderServiceReference.editCreditCardStandingOrderRequest request)
        {
            return base.Channel.editCreditCardStandingOrderAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
