//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorporateCreditCardServiceReference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class Exception
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class corporateProfileBean
    {
        
        private string corporateCivilIDField;
        
        private string corporateNameEnField;
        
        private string corporateNameArField;
        
        private string embossingNameField;
        
        private long rimCodeField;
        
        private string relationshipNoField;
        
        private string customerNoField;
        
        private string billingAccountNoField;
        
        private string kfhAccountNoField;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string corporateCivilID
        {
            get
            {
                return this.corporateCivilIDField;
            }
            set
            {
                this.corporateCivilIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string corporateNameEn
        {
            get
            {
                return this.corporateNameEnField;
            }
            set
            {
                this.corporateNameEnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string corporateNameAr
        {
            get
            {
                return this.corporateNameArField;
            }
            set
            {
                this.corporateNameArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string embossingName
        {
            get
            {
                return this.embossingNameField;
            }
            set
            {
                this.embossingNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long rimCode
        {
            get
            {
                return this.rimCodeField;
            }
            set
            {
                this.rimCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string relationshipNo
        {
            get
            {
                return this.relationshipNoField;
            }
            set
            {
                this.relationshipNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string customerNo
        {
            get
            {
                return this.customerNoField;
            }
            set
            {
                this.customerNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string billingAccountNo
        {
            get
            {
                return this.billingAccountNoField;
            }
            set
            {
                this.billingAccountNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string kfhAccountNo
        {
            get
            {
                return this.kfhAccountNoField;
            }
            set
            {
                this.kfhAccountNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string addressLine1
        {
            get
            {
                return this.addressLine1Field;
            }
            set
            {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string addressLine2
        {
            get
            {
                return this.addressLine2Field;
            }
            set
            {
                this.addressLine2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(corporateCardListWithProfileDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class ArrayOfCreditCard
    {
        
        private creditCard[] creditCardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CreditCard", IsNullable=true, Order=0)]
        public creditCard[] CreditCard
        {
            get
            {
                return this.creditCardField;
            }
            set
            {
                this.creditCardField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class creditCard
    {
        
        private string cardNoField;
        
        private int cardStatusField;
        
        private double approvedLimitField;
        
        private System.DateTime expiryField;
        
        private bool expiryFieldSpecified;
        
        private string bankAcctNoField;
        
        private long requestIDField;
        
        private System.DateTime requestDateField;
        
        private bool requestDateFieldSpecified;
        
        private int cardTypeField;
        
        private double limitField;
        
        private string civilIDField;
        
        private int branchIDField;
        
        private string tellerIDField;
        
        private System.DateTime approveDateField;
        
        private bool approveDateFieldSpecified;
        
        private int servicePeriodField;
        
        private string remarkField;
        
        private int photoField;
        
        private string depositNumberField;
        
        private int depositAmountField;
        
        private long pOBoxField;
        
        private string cityField;
        
        private long postCodeField;
        
        private string streetField;
        
        private string continuation_1Field;
        
        private string continuation_2Field;
        
        private long mobileField;
        
        private long homePhoneField;
        
        private long workPhoneField;
        
        private double salaryField;
        
        private int murabahaInstallmentsField;
        
        private int realEstateInstallmentsField;
        
        private int requestedLimitField;
        
        private long sellerIDField;
        
        private string faxReferenceField;
        
        private string fdAccountNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string cardNo
        {
            get
            {
                return this.cardNoField;
            }
            set
            {
                this.cardNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int cardStatus
        {
            get
            {
                return this.cardStatusField;
            }
            set
            {
                this.cardStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double approvedLimit
        {
            get
            {
                return this.approvedLimitField;
            }
            set
            {
                this.approvedLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime expiry
        {
            get
            {
                return this.expiryField;
            }
            set
            {
                this.expiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expirySpecified
        {
            get
            {
                return this.expiryFieldSpecified;
            }
            set
            {
                this.expiryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string bankAcctNo
        {
            get
            {
                return this.bankAcctNoField;
            }
            set
            {
                this.bankAcctNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long requestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime requestDate
        {
            get
            {
                return this.requestDateField;
            }
            set
            {
                this.requestDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requestDateSpecified
        {
            get
            {
                return this.requestDateFieldSpecified;
            }
            set
            {
                this.requestDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int cardType
        {
            get
            {
                return this.cardTypeField;
            }
            set
            {
                this.cardTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double limit
        {
            get
            {
                return this.limitField;
            }
            set
            {
                this.limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string civilID
        {
            get
            {
                return this.civilIDField;
            }
            set
            {
                this.civilIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int branchID
        {
            get
            {
                return this.branchIDField;
            }
            set
            {
                this.branchIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string tellerID
        {
            get
            {
                return this.tellerIDField;
            }
            set
            {
                this.tellerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime ApproveDate
        {
            get
            {
                return this.approveDateField;
            }
            set
            {
                this.approveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApproveDateSpecified
        {
            get
            {
                return this.approveDateFieldSpecified;
            }
            set
            {
                this.approveDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int servicePeriod
        {
            get
            {
                return this.servicePeriodField;
            }
            set
            {
                this.servicePeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string remark
        {
            get
            {
                return this.remarkField;
            }
            set
            {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int photo
        {
            get
            {
                return this.photoField;
            }
            set
            {
                this.photoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string depositNumber
        {
            get
            {
                return this.depositNumberField;
            }
            set
            {
                this.depositNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int depositAmount
        {
            get
            {
                return this.depositAmountField;
            }
            set
            {
                this.depositAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public long POBox
        {
            get
            {
                return this.pOBoxField;
            }
            set
            {
                this.pOBoxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public long postCode
        {
            get
            {
                return this.postCodeField;
            }
            set
            {
                this.postCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string continuation_1
        {
            get
            {
                return this.continuation_1Field;
            }
            set
            {
                this.continuation_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string continuation_2
        {
            get
            {
                return this.continuation_2Field;
            }
            set
            {
                this.continuation_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public long mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public long homePhone
        {
            get
            {
                return this.homePhoneField;
            }
            set
            {
                this.homePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public long workPhone
        {
            get
            {
                return this.workPhoneField;
            }
            set
            {
                this.workPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public double salary
        {
            get
            {
                return this.salaryField;
            }
            set
            {
                this.salaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public int murabahaInstallments
        {
            get
            {
                return this.murabahaInstallmentsField;
            }
            set
            {
                this.murabahaInstallmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public int realEstateInstallments
        {
            get
            {
                return this.realEstateInstallmentsField;
            }
            set
            {
                this.realEstateInstallmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public int requestedLimit
        {
            get
            {
                return this.requestedLimitField;
            }
            set
            {
                this.requestedLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public long sellerID
        {
            get
            {
                return this.sellerIDField;
            }
            set
            {
                this.sellerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string faxReference
        {
            get
            {
                return this.faxReferenceField;
            }
            set
            {
                this.faxReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string fdAccountNumber
        {
            get
            {
                return this.fdAccountNumberField;
            }
            set
            {
                this.fdAccountNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class corporateCardListWithProfileDTO : ArrayOfCreditCard
    {
        
        private corporateProfileBean corporateProfileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public corporateProfileBean corporateProfile
        {
            get
            {
                return this.corporateProfileField;
            }
            set
            {
                this.corporateProfileField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.openuri.org/", ConfigurationName="CorporateCreditCardServiceReference.CorporateCreditCardService")]
    public interface CorporateCreditCardService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/CorporateCreditCardService/getCorporateCardsRequest", ReplyAction="http://www.openuri.org/CorporateCreditCardService/getCorporateCardsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CorporateCreditCardServiceReference.Exception), Action="http://www.openuri.org/CorporateCreditCardService/getCorporateCards/Fault/Excepti" +
            "on", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CorporateCreditCardServiceReference.getCorporateCardsResponse> getCorporateCardsAsync(CorporateCreditCardServiceReference.getCorporateCardsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/CorporateCreditCardService/getCorporateProfileRequest", ReplyAction="http://www.openuri.org/CorporateCreditCardService/getCorporateProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CorporateCreditCardServiceReference.Exception), Action="http://www.openuri.org/CorporateCreditCardService/getCorporateProfile/Fault/Excep" +
            "tion", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CorporateCreditCardServiceReference.getCorporateProfileResponse> getCorporateProfileAsync(CorporateCreditCardServiceReference.getCorporateProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/CorporateCreditCardService/performCorporateProfileBoarding" +
            "Request", ReplyAction="http://www.openuri.org/CorporateCreditCardService/performCorporateProfileBoarding" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(CorporateCreditCardServiceReference.Exception), Action="http://www.openuri.org/CorporateCreditCardService/performCorporateProfileBoarding" +
            "/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CorporateCreditCardServiceReference.performCorporateProfileBoardingResponse> performCorporateProfileBoardingAsync(CorporateCreditCardServiceReference.performCorporateProfileBoardingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/CorporateCreditCardService/updateCorporateProfileRequest", ReplyAction="http://www.openuri.org/CorporateCreditCardService/updateCorporateProfileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CorporateCreditCardServiceReference.updateCorporateProfileResponse> updateCorporateProfileAsync(CorporateCreditCardServiceReference.updateCorporateProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/CorporateCreditCardService/getCorporateGlobalLimitRequest", ReplyAction="http://www.openuri.org/CorporateCreditCardService/getCorporateGlobalLimitResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(CorporateCreditCardServiceReference.Exception), Action="http://www.openuri.org/CorporateCreditCardService/getCorporateGlobalLimit/Fault/E" +
            "xception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CorporateCreditCardServiceReference.getCorporateGlobalLimitResponse> getCorporateGlobalLimitAsync(CorporateCreditCardServiceReference.getCorporateGlobalLimitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/CorporateCreditCardService/updateCorporateUndisbursedAmtRe" +
            "quest", ReplyAction="http://www.openuri.org/CorporateCreditCardService/updateCorporateUndisbursedAmtRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CorporateCreditCardServiceReference.Exception), Action="http://www.openuri.org/CorporateCreditCardService/updateCorporateUndisbursedAmt/F" +
            "ault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CorporateCreditCardServiceReference.updateCorporateUndisbursedAmtResponse> updateCorporateUndisbursedAmtAsync(CorporateCreditCardServiceReference.updateCorporateUndisbursedAmtRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCorporateCards", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getCorporateCardsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string corpCivilID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=1)]
        public string relationshipNo;
        
        public getCorporateCardsRequest()
        {
        }
        
        public getCorporateCardsRequest(string corpCivilID, string relationshipNo)
        {
            this.corpCivilID = corpCivilID;
            this.relationshipNo = relationshipNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCorporateCardsResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getCorporateCardsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public CorporateCreditCardServiceReference.corporateCardListWithProfileDTO getCorporateCards;
        
        public getCorporateCardsResponse()
        {
        }
        
        public getCorporateCardsResponse(CorporateCreditCardServiceReference.corporateCardListWithProfileDTO getCorporateCards)
        {
            this.getCorporateCards = getCorporateCards;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCorporateProfile", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getCorporateProfileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string corpCivilID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=1)]
        public string relationshipNo;
        
        public getCorporateProfileRequest()
        {
        }
        
        public getCorporateProfileRequest(string corpCivilID, string relationshipNo)
        {
            this.corpCivilID = corpCivilID;
            this.relationshipNo = relationshipNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCorporateProfileResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getCorporateProfileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public CorporateCreditCardServiceReference.corporateProfileBean getCorporateProfile;
        
        public getCorporateProfileResponse()
        {
        }
        
        public getCorporateProfileResponse(CorporateCreditCardServiceReference.corporateProfileBean getCorporateProfile)
        {
            this.getCorporateProfile = getCorporateProfile;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class corporateProfileRequest
    {
        
        private int organizationField;
        
        private string corporateNameEnField;
        
        private string corporateNameArField;
        
        private string embossingNameField;
        
        private long rimCodeField;
        
        private string corporateCivilIDField;
        
        private string kfhAccountNumberField;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string addressLine3Field;
        
        private string addressLine4Field;
        
        private string cityField;
        
        private string countryField;
        
        private string countryCodeField;
        
        private string postalCodeField;
        
        private string phoneNumberField;
        
        private string workPhoneNumberField;
        
        private string mobilePhoneNumberField;
        
        private string emailField;
        
        private string authCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int organization
        {
            get
            {
                return this.organizationField;
            }
            set
            {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string corporateNameEn
        {
            get
            {
                return this.corporateNameEnField;
            }
            set
            {
                this.corporateNameEnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string corporateNameAr
        {
            get
            {
                return this.corporateNameArField;
            }
            set
            {
                this.corporateNameArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string embossingName
        {
            get
            {
                return this.embossingNameField;
            }
            set
            {
                this.embossingNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long rimCode
        {
            get
            {
                return this.rimCodeField;
            }
            set
            {
                this.rimCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string corporateCivilID
        {
            get
            {
                return this.corporateCivilIDField;
            }
            set
            {
                this.corporateCivilIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string kfhAccountNumber
        {
            get
            {
                return this.kfhAccountNumberField;
            }
            set
            {
                this.kfhAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string addressLine1
        {
            get
            {
                return this.addressLine1Field;
            }
            set
            {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string addressLine2
        {
            get
            {
                return this.addressLine2Field;
            }
            set
            {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string addressLine3
        {
            get
            {
                return this.addressLine3Field;
            }
            set
            {
                this.addressLine3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string addressLine4
        {
            get
            {
                return this.addressLine4Field;
            }
            set
            {
                this.addressLine4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string countryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string postalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string phoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string workPhoneNumber
        {
            get
            {
                return this.workPhoneNumberField;
            }
            set
            {
                this.workPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string mobilePhoneNumber
        {
            get
            {
                return this.mobilePhoneNumberField;
            }
            set
            {
                this.mobilePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string authCriteria
        {
            get
            {
                return this.authCriteriaField;
            }
            set
            {
                this.authCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class corporateProfileResponse
    {
        
        private enumStatus statusField;
        
        private bool statusFieldSpecified;
        
        private string descriptionField;
        
        private string customerNumberField;
        
        private string relationshipNumberField;
        
        private string billingAcctNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public enumStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string customerNumber
        {
            get
            {
                return this.customerNumberField;
            }
            set
            {
                this.customerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string relationshipNumber
        {
            get
            {
                return this.relationshipNumberField;
            }
            set
            {
                this.relationshipNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string billingAcctNumber
        {
            get
            {
                return this.billingAcctNumberField;
            }
            set
            {
                this.billingAcctNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public enum enumStatus
    {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        FAILED,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="performCorporateProfileBoarding", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class performCorporateProfileBoardingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public CorporateCreditCardServiceReference.corporateProfileRequest corporateProfileRequest;
        
        public performCorporateProfileBoardingRequest()
        {
        }
        
        public performCorporateProfileBoardingRequest(CorporateCreditCardServiceReference.corporateProfileRequest corporateProfileRequest)
        {
            this.corporateProfileRequest = corporateProfileRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="performCorporateProfileBoardingResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class performCorporateProfileBoardingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public CorporateCreditCardServiceReference.corporateProfileResponse createCorporateProfile;
        
        public performCorporateProfileBoardingResponse()
        {
        }
        
        public performCorporateProfileBoardingResponse(CorporateCreditCardServiceReference.corporateProfileResponse createCorporateProfile)
        {
            this.createCorporateProfile = createCorporateProfile;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(updateCorporateUndisbursedAmtResultDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class operationResult
    {
        
        private bool isSuccessfulField;
        
        private string statusField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool isSuccessful
        {
            get
            {
                return this.isSuccessfulField;
            }
            set
            {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class updateCorporateUndisbursedAmtResultDTO : operationResult
    {
        
        private double amountField;
        
        private double undisbursedAmountField;
        
        private string referenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double undisbursedAmount
        {
            get
            {
                return this.undisbursedAmountField;
            }
            set
            {
                this.undisbursedAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string referenceNo
        {
            get
            {
                return this.referenceNoField;
            }
            set
            {
                this.referenceNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCorporateProfile", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class updateCorporateProfileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public int organization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=1)]
        public string corpCivilID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=2)]
        public string embossingName;
        
        public updateCorporateProfileRequest()
        {
        }
        
        public updateCorporateProfileRequest(int organization, string corpCivilID, string embossingName)
        {
            this.organization = organization;
            this.corpCivilID = corpCivilID;
            this.embossingName = embossingName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCorporateProfileResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class updateCorporateProfileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public CorporateCreditCardServiceReference.operationResult updateCorporateProfile;
        
        public updateCorporateProfileResponse()
        {
        }
        
        public updateCorporateProfileResponse(CorporateCreditCardServiceReference.operationResult updateCorporateProfile)
        {
            this.updateCorporateProfile = updateCorporateProfile;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class creditCardCorporateLimitsDTO
    {
        
        private corpCreditCardGlobalLimitDTO[] corpCreditCardGlobalLimitDTOField;
        
        private double totalUsedLimitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("corpCreditCardGlobalLimitDTO", Order=0)]
        public corpCreditCardGlobalLimitDTO[] corpCreditCardGlobalLimitDTO
        {
            get
            {
                return this.corpCreditCardGlobalLimitDTOField;
            }
            set
            {
                this.corpCreditCardGlobalLimitDTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double totalUsedLimit
        {
            get
            {
                return this.totalUsedLimitField;
            }
            set
            {
                this.totalUsedLimitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class corpCreditCardGlobalLimitDTO
    {
        
        private string commitmentTypeField;
        
        private string commitmentNoField;
        
        private double amountField;
        
        private double undisbursedAmountField;
        
        private System.DateTime maturityDateField;
        
        private bool maturityDateFieldSpecified;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string commitmentType
        {
            get
            {
                return this.commitmentTypeField;
            }
            set
            {
                this.commitmentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string commitmentNo
        {
            get
            {
                return this.commitmentNoField;
            }
            set
            {
                this.commitmentNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double undisbursedAmount
        {
            get
            {
                return this.undisbursedAmountField;
            }
            set
            {
                this.undisbursedAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime maturityDate
        {
            get
            {
                return this.maturityDateField;
            }
            set
            {
                this.maturityDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maturityDateSpecified
        {
            get
            {
                return this.maturityDateFieldSpecified;
            }
            set
            {
                this.maturityDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCorporateGlobalLimit", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getCorporateGlobalLimitRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string corpCivilID;
        
        public getCorporateGlobalLimitRequest()
        {
        }
        
        public getCorporateGlobalLimitRequest(string corpCivilID)
        {
            this.corpCivilID = corpCivilID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCorporateGlobalLimitResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getCorporateGlobalLimitResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public CorporateCreditCardServiceReference.creditCardCorporateLimitsDTO getCorporateGlobalLimit;
        
        public getCorporateGlobalLimitResponse()
        {
        }
        
        public getCorporateGlobalLimitResponse(CorporateCreditCardServiceReference.creditCardCorporateLimitsDTO getCorporateGlobalLimit)
        {
            this.getCorporateGlobalLimit = getCorporateGlobalLimit;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class updateCorporateUndisbursedAmtReqDTO
    {
        
        private string commitmentTypeField;
        
        private string commitmentNoField;
        
        private string currencyField;
        
        private string descriptionField;
        
        private double amountField;
        
        private int employeeIDField;
        
        private int branchNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string commitmentType
        {
            get
            {
                return this.commitmentTypeField;
            }
            set
            {
                this.commitmentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string commitmentNo
        {
            get
            {
                return this.commitmentNoField;
            }
            set
            {
                this.commitmentNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int employeeID
        {
            get
            {
                return this.employeeIDField;
            }
            set
            {
                this.employeeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int branchNo
        {
            get
            {
                return this.branchNoField;
            }
            set
            {
                this.branchNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCorporateUndisbursedAmt", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class updateCorporateUndisbursedAmtRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public CorporateCreditCardServiceReference.updateCorporateUndisbursedAmtReqDTO updateCorporateUndisbursedAmtReqDTO;
        
        public updateCorporateUndisbursedAmtRequest()
        {
        }
        
        public updateCorporateUndisbursedAmtRequest(CorporateCreditCardServiceReference.updateCorporateUndisbursedAmtReqDTO updateCorporateUndisbursedAmtReqDTO)
        {
            this.updateCorporateUndisbursedAmtReqDTO = updateCorporateUndisbursedAmtReqDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCorporateUndisbursedAmtResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class updateCorporateUndisbursedAmtResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public CorporateCreditCardServiceReference.updateCorporateUndisbursedAmtResultDTO updateCorporateUndisbursedAmt;
        
        public updateCorporateUndisbursedAmtResponse()
        {
        }
        
        public updateCorporateUndisbursedAmtResponse(CorporateCreditCardServiceReference.updateCorporateUndisbursedAmtResultDTO updateCorporateUndisbursedAmt)
        {
            this.updateCorporateUndisbursedAmt = updateCorporateUndisbursedAmt;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface CorporateCreditCardServiceChannel : CorporateCreditCardServiceReference.CorporateCreditCardService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class CorporateCreditCardServiceClient : System.ServiceModel.ClientBase<CorporateCreditCardServiceReference.CorporateCreditCardService>, CorporateCreditCardServiceReference.CorporateCreditCardService
    {
        
        public CorporateCreditCardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<CorporateCreditCardServiceReference.getCorporateCardsResponse> getCorporateCardsAsync(CorporateCreditCardServiceReference.getCorporateCardsRequest request)
        {
            return base.Channel.getCorporateCardsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CorporateCreditCardServiceReference.getCorporateProfileResponse> getCorporateProfileAsync(CorporateCreditCardServiceReference.getCorporateProfileRequest request)
        {
            return base.Channel.getCorporateProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<CorporateCreditCardServiceReference.performCorporateProfileBoardingResponse> performCorporateProfileBoardingAsync(CorporateCreditCardServiceReference.performCorporateProfileBoardingRequest request)
        {
            return base.Channel.performCorporateProfileBoardingAsync(request);
        }
        
        public System.Threading.Tasks.Task<CorporateCreditCardServiceReference.updateCorporateProfileResponse> updateCorporateProfileAsync(CorporateCreditCardServiceReference.updateCorporateProfileRequest request)
        {
            return base.Channel.updateCorporateProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<CorporateCreditCardServiceReference.getCorporateGlobalLimitResponse> getCorporateGlobalLimitAsync(CorporateCreditCardServiceReference.getCorporateGlobalLimitRequest request)
        {
            return base.Channel.getCorporateGlobalLimitAsync(request);
        }
        
        public System.Threading.Tasks.Task<CorporateCreditCardServiceReference.updateCorporateUndisbursedAmtResponse> updateCorporateUndisbursedAmtAsync(CorporateCreditCardServiceReference.updateCorporateUndisbursedAmtRequest request)
        {
            return base.Channel.updateCorporateUndisbursedAmtAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
