//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCardDelegationServiceReference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class Exception
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class creditCardResultDTO
    {
        
        private bool isSuccessfulField;
        
        private string statusField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool isSuccessful
        {
            get
            {
                return this.isSuccessfulField;
            }
            set
            {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.openuri.org/", ConfigurationName="CreditCardDelegationServiceReference.CreditCardDelegationServicesService")]
    public interface CreditCardDelegationServicesService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/CreditCardDelegationServicesService/delegateRequest", ReplyAction="http://www.openuri.org/CreditCardDelegationServicesService/delegateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CreditCardDelegationServiceReference.Exception), Action="http://www.openuri.org/CreditCardDelegationServicesService/delegate/Fault/Excepti" +
            "on", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CreditCardDelegationServiceReference.delegateResponse> delegateAsync(CreditCardDelegationServiceReference.delegateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/CreditCardDelegationServicesService/updateDelegateRequest", ReplyAction="http://www.openuri.org/CreditCardDelegationServicesService/updateDelegateResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(CreditCardDelegationServiceReference.Exception), Action="http://www.openuri.org/CreditCardDelegationServicesService/updateDelegate/Fault/E" +
            "xception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CreditCardDelegationServiceReference.updateDelegateResponse> updateDelegateAsync(CreditCardDelegationServiceReference.updateDelegateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/CreditCardDelegationServicesService/getDelegationListReque" +
            "st", ReplyAction="http://www.openuri.org/CreditCardDelegationServicesService/getDelegationListRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CreditCardDelegationServiceReference.Exception), Action="http://www.openuri.org/CreditCardDelegationServicesService/getDelegationList/Faul" +
            "t/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CreditCardDelegationServiceReference.getDelegationListResponse> getDelegationListAsync(CreditCardDelegationServiceReference.getDelegationListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delegate", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class delegateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string requestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=1)]
        public string userID;
        
        public delegateRequest()
        {
        }
        
        public delegateRequest(string requestID, string userID)
        {
            this.requestID = requestID;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delegateResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class delegateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public CreditCardDelegationServiceReference.creditCardResultDTO delegateResult;
        
        public delegateResponse()
        {
        }
        
        public delegateResponse(CreditCardDelegationServiceReference.creditCardResultDTO delegateResult)
        {
            this.delegateResult = delegateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDelegate", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class updateDelegateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string requestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=1)]
        public string userID;
        
        public updateDelegateRequest()
        {
        }
        
        public updateDelegateRequest(string requestID, string userID)
        {
            this.requestID = requestID;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDelegateResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class updateDelegateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public CreditCardDelegationServiceReference.creditCardResultDTO updateDelegateResult;
        
        public updateDelegateResponse()
        {
        }
        
        public updateDelegateResponse(CreditCardDelegationServiceReference.creditCardResultDTO updateDelegateResult)
        {
            this.updateDelegateResult = updateDelegateResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class creditCardDelegationList
    {
        
        private string userIDField;
        
        private string userNameField;
        
        private string groupIDField;
        
        private string groupNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string groupID
        {
            get
            {
                return this.groupIDField;
            }
            set
            {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string groupName
        {
            get
            {
                return this.groupNameField;
            }
            set
            {
                this.groupNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDelegationList", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getDelegationListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string branchID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=1)]
        public string percentage;
        
        public getDelegationListRequest()
        {
        }
        
        public getDelegationListRequest(string branchID, string percentage)
        {
            this.branchID = branchID;
            this.percentage = percentage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDelegationListResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getDelegationListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CreditCardDelegationList")]
        public CreditCardDelegationServiceReference.creditCardDelegationList[] getDelegationListResult;
        
        public getDelegationListResponse()
        {
        }
        
        public getDelegationListResponse(CreditCardDelegationServiceReference.creditCardDelegationList[] getDelegationListResult)
        {
            this.getDelegationListResult = getDelegationListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface CreditCardDelegationServicesServiceChannel : CreditCardDelegationServiceReference.CreditCardDelegationServicesService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class CreditCardDelegationServicesServiceClient : System.ServiceModel.ClientBase<CreditCardDelegationServiceReference.CreditCardDelegationServicesService>, CreditCardDelegationServiceReference.CreditCardDelegationServicesService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CreditCardDelegationServicesServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CreditCardDelegationServicesServiceClient.GetBindingForEndpoint(endpointConfiguration), CreditCardDelegationServicesServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditCardDelegationServicesServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CreditCardDelegationServicesServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditCardDelegationServicesServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CreditCardDelegationServicesServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditCardDelegationServicesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<CreditCardDelegationServiceReference.delegateResponse> delegateAsync(CreditCardDelegationServiceReference.delegateRequest request)
        {
            return base.Channel.delegateAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditCardDelegationServiceReference.updateDelegateResponse> updateDelegateAsync(CreditCardDelegationServiceReference.updateDelegateRequest request)
        {
            return base.Channel.updateDelegateAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditCardDelegationServiceReference.getDelegationListResponse> getDelegationListAsync(CreditCardDelegationServiceReference.getDelegationListRequest request)
        {
            return base.Channel.getDelegationListAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CreditCardDelegationServicesServiceSoap9))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditCardDelegationServicesServiceSoap3))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditCardDelegationServicesServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditCardDelegationServicesServiceSoap4))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditCardDelegationServicesServiceSoap2))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditCardDelegationServicesServiceSoap7))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditCardDelegationServicesServiceSoap8))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditCardDelegationServicesServiceSoap5))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditCardDelegationServicesServiceSoap6))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CreditCardDelegationServicesServiceSoap9))
            {
                return new System.ServiceModel.EndpointAddress("https://soa_apigw/kfhsoa/ws/CreditCardDelegationServicesService/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditCardDelegationServicesServiceSoap3))
            {
                return new System.ServiceModel.EndpointAddress("https://integration/ws/WLS_CreditCardDelegationServicesService.CreditCardDelegati" +
                        "onServicesServiceSoap/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditCardDelegationServicesServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://fzvdsoaap05:6655/ws/WLS_CreditCardDelegationServicesService.CreditCardDele" +
                        "gationServicesServiceSoap/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditCardDelegationServicesServiceSoap4))
            {
                return new System.ServiceModel.EndpointAddress("https://integration/ws/WLS_CreditCardDelegationServicesService/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditCardDelegationServicesServiceSoap2))
            {
                return new System.ServiceModel.EndpointAddress("http://fzvdsoaap05:6655/ws/WLS_CreditCardDelegationServicesService/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditCardDelegationServicesServiceSoap7))
            {
                return new System.ServiceModel.EndpointAddress("http://fzvdsoaap05:6655/kfhsoa/ws/CreditCardDelegationServicesService/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditCardDelegationServicesServiceSoap8))
            {
                return new System.ServiceModel.EndpointAddress("https://integration/kfhsoa/ws/CreditCardDelegationServicesService/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditCardDelegationServicesServiceSoap5))
            {
                return new System.ServiceModel.EndpointAddress("https://soa_apigw/ws/WLS_CreditCardDelegationServicesService.CreditCardDelegation" +
                        "ServicesServiceSoap/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditCardDelegationServicesServiceSoap6))
            {
                return new System.ServiceModel.EndpointAddress("https://soa_apigw/ws/WLS_CreditCardDelegationServicesService/1.0");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CreditCardDelegationServicesServiceSoap9,
            
            CreditCardDelegationServicesServiceSoap3,
            
            CreditCardDelegationServicesServiceSoap,
            
            CreditCardDelegationServicesServiceSoap4,
            
            CreditCardDelegationServicesServiceSoap2,
            
            CreditCardDelegationServicesServiceSoap7,
            
            CreditCardDelegationServicesServiceSoap8,
            
            CreditCardDelegationServicesServiceSoap5,
            
            CreditCardDelegationServicesServiceSoap6,
        }
    }
}
