//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCardUpdateProfileService
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.openuri.org/")]
    public partial class BusinessException
    {

        private string messageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.openuri.org/")]
    public partial class creditCardCustomerProfileBean
    {

        private string civilIDField;

        private string arabicNameField;

        private string areaField;

        private System.DateTime birthField;

        private bool birthFieldSpecified;

        private string blockNoField;

        private string buildNoField;

        private int countryField;

        private bool countryFieldSpecified;

        private string durationServiceField;

        private string emailField;

        private string employerAreaField;

        private string employerDepartmentField;

        private string employerNameField;

        private string employerSectionField;

        private string fileNoField;

        private string firstNameField;

        private string flatNoField;

        private string fullNameField;

        private int genderField;

        private bool genderFieldSpecified;

        private string holderNameField;

        private string lastNameField;

        private string middleNameField;

        private int nationalityField;

        private bool nationalityFieldSpecified;

        private string otherNameField;

        private string secondaryCivilIDField;

        private string streetField;

        private string titleField;

        private string customerNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string civilID
        {
            get
            {
                return this.civilIDField;
            }
            set
            {
                this.civilIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string arabicName
        {
            get
            {
                return this.arabicNameField;
            }
            set
            {
                this.arabicNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string area
        {
            get
            {
                return this.areaField;
            }
            set
            {
                this.areaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public System.DateTime birth
        {
            get
            {
                return this.birthField;
            }
            set
            {
                this.birthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthSpecified
        {
            get
            {
                return this.birthFieldSpecified;
            }
            set
            {
                this.birthFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string blockNo
        {
            get
            {
                return this.blockNoField;
            }
            set
            {
                this.blockNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string buildNo
        {
            get
            {
                return this.buildNoField;
            }
            set
            {
                this.buildNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public int country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countrySpecified
        {
            get
            {
                return this.countryFieldSpecified;
            }
            set
            {
                this.countryFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string durationService
        {
            get
            {
                return this.durationServiceField;
            }
            set
            {
                this.durationServiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string employerArea
        {
            get
            {
                return this.employerAreaField;
            }
            set
            {
                this.employerAreaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string employerDepartment
        {
            get
            {
                return this.employerDepartmentField;
            }
            set
            {
                this.employerDepartmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string employerName
        {
            get
            {
                return this.employerNameField;
            }
            set
            {
                this.employerNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string employerSection
        {
            get
            {
                return this.employerSectionField;
            }
            set
            {
                this.employerSectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public string fileNo
        {
            get
            {
                return this.fileNoField;
            }
            set
            {
                this.fileNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public string flatNo
        {
            get
            {
                return this.flatNoField;
            }
            set
            {
                this.flatNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public string fullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public int gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool genderSpecified
        {
            get
            {
                return this.genderFieldSpecified;
            }
            set
            {
                this.genderFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public string holderName
        {
            get
            {
                return this.holderNameField;
            }
            set
            {
                this.holderNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 19)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 20)]
        public string middleName
        {
            get
            {
                return this.middleNameField;
            }
            set
            {
                this.middleNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 21)]
        public int nationality
        {
            get
            {
                return this.nationalityField;
            }
            set
            {
                this.nationalityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nationalitySpecified
        {
            get
            {
                return this.nationalityFieldSpecified;
            }
            set
            {
                this.nationalityFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 22)]
        public string otherName
        {
            get
            {
                return this.otherNameField;
            }
            set
            {
                this.otherNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 23)]
        public string secondaryCivilID
        {
            get
            {
                return this.secondaryCivilIDField;
            }
            set
            {
                this.secondaryCivilIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 24)]
        public string street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 25)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 26)]
        public string customerNumber
        {
            get
            {
                return this.customerNumberField;
            }
            set
            {
                this.customerNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.openuri.org/")]
    public partial class creditCardCustomerProfileCriteriaDTO
    {

        private string searchCriteriaField;

        private string searchValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string searchCriteria
        {
            get
            {
                return this.searchCriteriaField;
            }
            set
            {
                this.searchCriteriaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string searchValue
        {
            get
            {
                return this.searchValueField;
            }
            set
            {
                this.searchValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.openuri.org/")]
    public partial class Exception
    {

        private string messageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.openuri.org/", ConfigurationName = "CreditCardUpdateProfileService.CreditCardUpdateProfileServicesService")]
    public interface CreditCardUpdateProfileServicesService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openuri.org/CreditCardUpdateProfileServicesService/getCreditCardCustom" +
            "erProfileRequest", ReplyAction = "http://www.openuri.org/CreditCardUpdateProfileServicesService/getCreditCardCustom" +
            "erProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CreditCardUpdateProfileService.BusinessException), Action = "http://www.openuri.org/CreditCardUpdateProfileServicesService/getCreditCardCustom" +
            "erProfile/Fault/BusinessException", Name = "BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<CreditCardUpdateProfileService.getCreditCardCustomerProfileResponse> getCreditCardCustomerProfileAsync(CreditCardUpdateProfileService.getCreditCardCustomerProfileRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openuri.org/CreditCardUpdateProfileServicesService/performAccountBoard" +
            "Request", ReplyAction = "http://www.openuri.org/CreditCardUpdateProfileServicesService/performAccountBoard" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(CreditCardUpdateProfileService.Exception), Action = "http://www.openuri.org/CreditCardUpdateProfileServicesService/performAccountBoard" +
            "/Fault/Exception", Name = "Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<CreditCardUpdateProfileService.performAccountBoardResponse> performAccountBoardAsync(CreditCardUpdateProfileService.performAccountBoardRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openuri.org/CreditCardUpdateProfileServicesService/updateCreditCardNoA" +
            "ndFDAcctNoRequest", ReplyAction = "http://www.openuri.org/CreditCardUpdateProfileServicesService/updateCreditCardNoA" +
            "ndFDAcctNoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CreditCardUpdateProfileService.BusinessException), Action = "http://www.openuri.org/CreditCardUpdateProfileServicesService/updateCreditCardNoA" +
            "ndFDAcctNo/Fault/BusinessException", Name = "BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<CreditCardUpdateProfileService.updateCreditCardNoAndFDAcctNoResponse> updateCreditCardNoAndFDAcctNoAsync(CreditCardUpdateProfileService.updateCreditCardNoAndFDAcctNoRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openuri.org/CreditCardUpdateProfileServicesService/updateCreditCardCus" +
            "tomerNoRequest", ReplyAction = "http://www.openuri.org/CreditCardUpdateProfileServicesService/updateCreditCardCus" +
            "tomerNoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<CreditCardUpdateProfileService.updateCreditCardCustomerNoResponse> updateCreditCardCustomerNoAsync(CreditCardUpdateProfileService.updateCreditCardCustomerNoRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openuri.org/CreditCardUpdateProfileServicesService/updateCreditCardAnd" +
            "ProfileRequest", ReplyAction = "http://www.openuri.org/CreditCardUpdateProfileServicesService/updateCreditCardAnd" +
            "ProfileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<CreditCardUpdateProfileService.updateCreditCardAndProfileResponse> updateCreditCardAndProfileAsync(CreditCardUpdateProfileService.updateCreditCardAndProfileRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openuri.org/CreditCardUpdateProfileServicesService/deleteCreditCardCus" +
            "tomerProfileRequest", ReplyAction = "http://www.openuri.org/CreditCardUpdateProfileServicesService/deleteCreditCardCus" +
            "tomerProfileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<CreditCardUpdateProfileService.deleteCreditCardCustomerProfileResponse> deleteCreditCardCustomerProfileAsync(CreditCardUpdateProfileService.deleteCreditCardCustomerProfileRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openuri.org/CreditCardUpdateProfileServicesService/updateCreditCardCus" +
            "tomerProfileRequest", ReplyAction = "http://www.openuri.org/CreditCardUpdateProfileServicesService/updateCreditCardCus" +
            "tomerProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CreditCardUpdateProfileService.Exception), Action = "http://www.openuri.org/CreditCardUpdateProfileServicesService/updateCreditCardCus" +
            "tomerProfile/Fault/Exception", Name = "Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<CreditCardUpdateProfileService.updateCreditCardCustomerProfileResponse> updateCreditCardCustomerProfileAsync(CreditCardUpdateProfileService.updateCreditCardCustomerProfileRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openuri.org/CreditCardUpdateProfileServicesService/insertCreditCardCus" +
            "tomerProfileRequest", ReplyAction = "http://www.openuri.org/CreditCardUpdateProfileServicesService/insertCreditCardCus" +
            "tomerProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CreditCardUpdateProfileService.Exception), Action = "http://www.openuri.org/CreditCardUpdateProfileServicesService/insertCreditCardCus" +
            "tomerProfile/Fault/Exception", Name = "Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<CreditCardUpdateProfileService.insertCreditCardCustomerProfileResponse> insertCreditCardCustomerProfileAsync(CreditCardUpdateProfileService.insertCreditCardCustomerProfileRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getCreditCardCustomerProfile", WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class getCreditCardCustomerProfileRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 0)]
        public CreditCardUpdateProfileService.creditCardCustomerProfileCriteriaDTO creditCardCustomerProfileCriteria;

        public getCreditCardCustomerProfileRequest()
        {
        }

        public getCreditCardCustomerProfileRequest(CreditCardUpdateProfileService.creditCardCustomerProfileCriteriaDTO creditCardCustomerProfileCriteria)
        {
            this.creditCardCustomerProfileCriteria = creditCardCustomerProfileCriteria;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getCreditCardCustomerProfileResponse", WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class getCreditCardCustomerProfileResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CreditCardCustomerProfileDTO")]
        public CreditCardUpdateProfileService.creditCardCustomerProfileBean[] getCreditCardCustomerProfileResult;

        public getCreditCardCustomerProfileResponse()
        {
        }

        public getCreditCardCustomerProfileResponse(CreditCardUpdateProfileService.creditCardCustomerProfileBean[] getCreditCardCustomerProfileResult)
        {
            this.getCreditCardCustomerProfileResult = getCreditCardCustomerProfileResult;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.openuri.org/")]
    public partial class accountBoardingRequest
    {
       
        private long requestIDField;

        private long primaryRequestIDField;

        private bool primaryRequestIDFieldSpecified;

        private string corpCivilIDField;

        private string customerRecordActionField;

        private string accountRecordActionField;

        private string embosserRecordActionField;

        private cardRequest[] cardRequestListField;

        private int organizationField;

        private string customerNumberField;

        private string uniqueIDField;

        private int vipStatusField;

        private string titleField;

        private string firstNameField;

        private string middleNameField;

        private string lastNameField;

        private int dateOfBirthField;

        private string genderCodeField;

        private string nationalityField;

        private string civilIDField;

        private string relativeNameField;

        private string addressLine1Field;

        private string addressLine2Field;

        private string addressLine3Field;

        private string addressLine4Field;

        private string cityField;

        private string countryField;

        private string countryCodeField;

        private string postalCodeField;

        private string homePhoneNumberField;

        private string workPhoneNumberField;

        private string mobilePhoneNumberField;

        private string emailField;

        private int accountLogoField;

        private int accountEmblemIDField;

        private string accountNumberField;

        private int creditLMTField;

        private string issuanceIDField;

        private string retailBankingACCNBRField;

        private int incomeField;

        private string staffIDField;

        private string cardTypeField;

        private string kfhCustomerField;

        private string kfhStaffField;

        private string promotionCodeField;

        private int productTypeField;

        private int serviceNumberField;

        private int serviceStartDateField;

        private int serviceExpiryDateField;

        private string embossedName1Field;

        private string embossedName2Field;

        private int issueBranch1STField;

        private int sameDayPlasticField;

        private bool pinMailerRequireField;

        private bool pinMailerRequireFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public long requestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public long primaryRequestID
        {
            get
            {
                return this.primaryRequestIDField;
            }
            set
            {
                this.primaryRequestIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool primaryRequestIDSpecified
        {
            get
            {
                return this.primaryRequestIDFieldSpecified;
            }
            set
            {
                this.primaryRequestIDFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string corpCivilID
        {
            get
            {
                return this.corpCivilIDField;
            }
            set
            {
                this.corpCivilIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string customerRecordAction
        {
            get
            {
                return this.customerRecordActionField;
            }
            set
            {
                this.customerRecordActionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string accountRecordAction
        {
            get
            {
                return this.accountRecordActionField;
            }
            set
            {
                this.accountRecordActionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string embosserRecordAction
        {
            get
            {
                return this.embosserRecordActionField;
            }
            set
            {
                this.embosserRecordActionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cardRequestList", Order = 6)]
        public cardRequest[] cardRequestList
        {
            get
            {
                return this.cardRequestListField;
            }
            set
            {
                this.cardRequestListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public int organization
        {
            get
            {
                return this.organizationField;
            }
            set
            {
                this.organizationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string customerNumber
        {
            get
            {
                return this.customerNumberField;
            }
            set
            {
                this.customerNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string uniqueID
        {
            get
            {
                return this.uniqueIDField;
            }
            set
            {
                this.uniqueIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public int vipStatus
        {
            get
            {
                return this.vipStatusField;
            }
            set
            {
                this.vipStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public string middleName
        {
            get
            {
                return this.middleNameField;
            }
            set
            {
                this.middleNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public int dateOfBirth
        {
            get
            {
                return this.dateOfBirthField;
            }
            set
            {
                this.dateOfBirthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public string genderCode
        {
            get
            {
                return this.genderCodeField;
            }
            set
            {
                this.genderCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public string nationality
        {
            get
            {
                return this.nationalityField;
            }
            set
            {
                this.nationalityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public string civilID
        {
            get
            {
                return this.civilIDField;
            }
            set
            {
                this.civilIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 19)]
        public string relativeName
        {
            get
            {
                return this.relativeNameField;
            }
            set
            {
                this.relativeNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 20)]
        public string addressLine1
        {
            get
            {
                return this.addressLine1Field;
            }
            set
            {
                this.addressLine1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 21)]
        public string addressLine2
        {
            get
            {
                return this.addressLine2Field;
            }
            set
            {
                this.addressLine2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 22)]
        public string addressLine3
        {
            get
            {
                return this.addressLine3Field;
            }
            set
            {
                this.addressLine3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 23)]
        public string addressLine4
        {
            get
            {
                return this.addressLine4Field;
            }
            set
            {
                this.addressLine4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 24)]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 25)]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 26)]
        public string countryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 27)]
        public string postalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 28)]
        public string homePhoneNumber
        {
            get
            {
                return this.homePhoneNumberField;
            }
            set
            {
                this.homePhoneNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 29)]
        public string workPhoneNumber
        {
            get
            {
                return this.workPhoneNumberField;
            }
            set
            {
                this.workPhoneNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 30)]
        public string mobilePhoneNumber
        {
            get
            {
                return this.mobilePhoneNumberField;
            }
            set
            {
                this.mobilePhoneNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 31)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 32)]
        public int accountLogo
        {
            get
            {
                return this.accountLogoField;
            }
            set
            {
                this.accountLogoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 33)]
        public int accountEmblemID
        {
            get
            {
                return this.accountEmblemIDField;
            }
            set
            {
                this.accountEmblemIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 34)]
        public string accountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 35)]
        public int creditLMT
        {
            get
            {
                return this.creditLMTField;
            }
            set
            {
                this.creditLMTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 36)]
        public string issuanceID
        {
            get
            {
                return this.issuanceIDField;
            }
            set
            {
                this.issuanceIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 37)]
        public string retailBankingACCNBR
        {
            get
            {
                return this.retailBankingACCNBRField;
            }
            set
            {
                this.retailBankingACCNBRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 38)]
        public int income
        {
            get
            {
                return this.incomeField;
            }
            set
            {
                this.incomeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 39)]
        public string staffID
        {
            get
            {
                return this.staffIDField;
            }
            set
            {
                this.staffIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 40)]
        public string cardType
        {
            get
            {
                return this.cardTypeField;
            }
            set
            {
                this.cardTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 41)]
        public string kfhCustomer
        {
            get
            {
                return this.kfhCustomerField;
            }
            set
            {
                this.kfhCustomerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 42)]
        public string kfhStaff
        {
            get
            {
                return this.kfhStaffField;
            }
            set
            {
                this.kfhStaffField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 43)]
        public string promotionCode
        {
            get
            {
                return this.promotionCodeField;
            }
            set
            {
                this.promotionCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 44)]
        public int productType
        {
            get
            {
                return this.productTypeField;
            }
            set
            {
                this.productTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 45)]
        public int serviceNumber
        {
            get
            {
                return this.serviceNumberField;
            }
            set
            {
                this.serviceNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 46)]
        public int serviceStartDate
        {
            get
            {
                return this.serviceStartDateField;
            }
            set
            {
                this.serviceStartDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 47)]
        public int serviceExpiryDate
        {
            get
            {
                return this.serviceExpiryDateField;
            }
            set
            {
                this.serviceExpiryDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 48)]
        public string embossedName1
        {
            get
            {
                return this.embossedName1Field;
            }
            set
            {
                this.embossedName1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 49)]
        public string embossedName2
        {
            get
            {
                return this.embossedName2Field;
            }
            set
            {
                this.embossedName2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 50)]
        public int issueBranch1ST
        {
            get
            {
                return this.issueBranch1STField;
            }
            set
            {
                this.issueBranch1STField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 51)]
        public int sameDayPlastic
        {
            get
            {
                return this.sameDayPlasticField;
            }
            set
            {
                this.sameDayPlasticField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 52)]
        public bool pinMailerRequire
        {
            get
            {
                return this.pinMailerRequireField;
            }
            set
            {
                this.pinMailerRequireField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pinMailerRequireSpecified
        {
            get
            {
                return this.pinMailerRequireFieldSpecified;
            }
            set
            {
                this.pinMailerRequireFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.openuri.org/")]
    public partial class cardRequest
    {

        private int cardLogoField;

        private int emblemIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public int cardLogo
        {
            get
            {
                return this.cardLogoField;
            }
            set
            {
                this.cardLogoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public int emblemID
        {
            get
            {
                return this.emblemIDField;
            }
            set
            {
                this.emblemIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.openuri.org/")]
    public partial class accountBoardingResponse
    {

        private string customerNumberField;

        private int accountLogoField;

        private string accountNumberField;

        private cardData[] cardDataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string customerNumber
        {
            get
            {
                return this.customerNumberField;
            }
            set
            {
                this.customerNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public int accountLogo
        {
            get
            {
                return this.accountLogoField;
            }
            set
            {
                this.accountLogoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string accountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cardData", Order = 3)]
        public cardData[] cardData
        {
            get
            {
                return this.cardDataField;
            }
            set
            {
                this.cardDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.openuri.org/")]
    public partial class cardData
    {

        private int cardLogoField;

        private string cardNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public int cardLogo
        {
            get
            {
                return this.cardLogoField;
            }
            set
            {
                this.cardLogoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string cardNumber
        {
            get
            {
                return this.cardNumberField;
            }
            set
            {
                this.cardNumberField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "performAccountBoard", WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class performAccountBoardRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 0)]
        public CreditCardUpdateProfileService.accountBoardingRequest accountBoardingRequest;

        public performAccountBoardRequest()
        {
        }

        public performAccountBoardRequest(CreditCardUpdateProfileService.accountBoardingRequest accountBoardingRequest)
        {
            this.accountBoardingRequest = accountBoardingRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "performAccountBoardResponse", WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class performAccountBoardResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 0)]
        public CreditCardUpdateProfileService.accountBoardingResponse performAccountBoardResult;

        public performAccountBoardResponse()
        {
        }

        public performAccountBoardResponse(CreditCardUpdateProfileService.accountBoardingResponse performAccountBoardResult)
        {
            this.performAccountBoardResult = performAccountBoardResult;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.openuri.org/")]
    public partial class creditCardResultDTO
    {

        private bool isSuccessfulField;

        private string statusField;

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public bool isSuccessful
        {
            get
            {
                return this.isSuccessfulField;
            }
            set
            {
                this.isSuccessfulField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "updateCreditCardNoAndFDAcctNo", WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class updateCreditCardNoAndFDAcctNoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 0)]
        public string requestId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 1)]
        public string fdAccountNumber;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 2)]
        public string cardNumber;

        public updateCreditCardNoAndFDAcctNoRequest()
        {
        }

        public updateCreditCardNoAndFDAcctNoRequest(string requestId, string fdAccountNumber, string cardNumber)
        {
            this.requestId = requestId;
            this.fdAccountNumber = fdAccountNumber;
            this.cardNumber = cardNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "updateCreditCardNoAndFDAcctNoResponse", WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class updateCreditCardNoAndFDAcctNoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 0)]
        public CreditCardUpdateProfileService.creditCardResultDTO updateCreditCardNoAndFDAcctNoResult;

        public updateCreditCardNoAndFDAcctNoResponse()
        {
        }

        public updateCreditCardNoAndFDAcctNoResponse(CreditCardUpdateProfileService.creditCardResultDTO updateCreditCardNoAndFDAcctNoResult)
        {
            this.updateCreditCardNoAndFDAcctNoResult = updateCreditCardNoAndFDAcctNoResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "updateCreditCardCustomerNo", WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class updateCreditCardCustomerNoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 0)]
        public string civilId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 1)]
        public string customerNumber;

        public updateCreditCardCustomerNoRequest()
        {
        }

        public updateCreditCardCustomerNoRequest(string civilId, string customerNumber)
        {
            this.civilId = civilId;
            this.customerNumber = customerNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "updateCreditCardCustomerNoResponse", WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class updateCreditCardCustomerNoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 0)]
        public CreditCardUpdateProfileService.creditCardResultDTO updateCreditCardCustomerNoResult;

        public updateCreditCardCustomerNoResponse()
        {
        }

        public updateCreditCardCustomerNoResponse(CreditCardUpdateProfileService.creditCardResultDTO updateCreditCardCustomerNoResult)
        {
            this.updateCreditCardCustomerNoResult = updateCreditCardCustomerNoResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "updateCreditCardAndProfile", WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class updateCreditCardAndProfileRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 0)]
        public string requestId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 1)]
        public string fdAccountNumber;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 2)]
        public string cardNumber;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 3)]
        public string customerNumber;

        public updateCreditCardAndProfileRequest()
        {
        }

        public updateCreditCardAndProfileRequest(string requestId, string fdAccountNumber, string cardNumber, string customerNumber)
        {
            this.requestId = requestId;
            this.fdAccountNumber = fdAccountNumber;
            this.cardNumber = cardNumber;
            this.customerNumber = customerNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "updateCreditCardAndProfileResponse", WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class updateCreditCardAndProfileResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 0)]
        public CreditCardUpdateProfileService.creditCardResultDTO updateCreditCardAndProfileResult;

        public updateCreditCardAndProfileResponse()
        {
        }

        public updateCreditCardAndProfileResponse(CreditCardUpdateProfileService.creditCardResultDTO updateCreditCardAndProfileResult)
        {
            this.updateCreditCardAndProfileResult = updateCreditCardAndProfileResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "deleteCreditCardCustomerProfile", WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class deleteCreditCardCustomerProfileRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 0)]
        public string civilID;

        public deleteCreditCardCustomerProfileRequest()
        {
        }

        public deleteCreditCardCustomerProfileRequest(string civilID)
        {
            this.civilID = civilID;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "deleteCreditCardCustomerProfileResponse", WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class deleteCreditCardCustomerProfileResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 0)]
        public CreditCardUpdateProfileService.creditCardResultDTO deleteCreditCardCustomerProfileResult;

        public deleteCreditCardCustomerProfileResponse()
        {
        }

        public deleteCreditCardCustomerProfileResponse(CreditCardUpdateProfileService.creditCardResultDTO deleteCreditCardCustomerProfileResult)
        {
            this.deleteCreditCardCustomerProfileResult = deleteCreditCardCustomerProfileResult;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.openuri.org/")]
    public partial class creditCardCustomerProfileDTO
    {

        private string civilIDField;

        private string titleField;

        private string fullNameField;

        private string arabicNameField;

        private string otherNameField;

        private string holderNameField;

        private System.DateTime birthField;

        private bool birthFieldSpecified;

        private string st_birthField;

        private string countryField;

        private string nationalityField;

        private string employerNameField;

        private string genderField;

        private string firstNameField;

        private string middleNameField;

        private string lastNameField;

        private string fileNoField;

        private string emailField;

        private string areaField;

        private string streetField;

        private string blockNoField;

        private string buildNoField;

        private string flatNoField;

        private string employerSectionField;

        private string employerDepartmentField;

        private string employerAreaField;

        private string durationServiceField;

        private string secondaryCivilIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string civilID
        {
            get
            {
                return this.civilIDField;
            }
            set
            {
                this.civilIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string fullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string arabicName
        {
            get
            {
                return this.arabicNameField;
            }
            set
            {
                this.arabicNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string otherName
        {
            get
            {
                return this.otherNameField;
            }
            set
            {
                this.otherNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string holderName
        {
            get
            {
                return this.holderNameField;
            }
            set
            {
                this.holderNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public System.DateTime birth
        {
            get
            {
                return this.birthField;
            }
            set
            {
                this.birthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthSpecified
        {
            get
            {
                return this.birthFieldSpecified;
            }
            set
            {
                this.birthFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string st_birth
        {
            get
            {
                return this.st_birthField;
            }
            set
            {
                this.st_birthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string nationality
        {
            get
            {
                return this.nationalityField;
            }
            set
            {
                this.nationalityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string employerName
        {
            get
            {
                return this.employerNameField;
            }
            set
            {
                this.employerNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public string middleName
        {
            get
            {
                return this.middleNameField;
            }
            set
            {
                this.middleNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public string fileNo
        {
            get
            {
                return this.fileNoField;
            }
            set
            {
                this.fileNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public string area
        {
            get
            {
                return this.areaField;
            }
            set
            {
                this.areaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public string street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 19)]
        public string blockNo
        {
            get
            {
                return this.blockNoField;
            }
            set
            {
                this.blockNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 20)]
        public string buildNo
        {
            get
            {
                return this.buildNoField;
            }
            set
            {
                this.buildNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 21)]
        public string flatNo
        {
            get
            {
                return this.flatNoField;
            }
            set
            {
                this.flatNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 22)]
        public string employerSection
        {
            get
            {
                return this.employerSectionField;
            }
            set
            {
                this.employerSectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 23)]
        public string employerDepartment
        {
            get
            {
                return this.employerDepartmentField;
            }
            set
            {
                this.employerDepartmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 24)]
        public string employerArea
        {
            get
            {
                return this.employerAreaField;
            }
            set
            {
                this.employerAreaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 25)]
        public string durationService
        {
            get
            {
                return this.durationServiceField;
            }
            set
            {
                this.durationServiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 26)]
        public string secondaryCivilID
        {
            get
            {
                return this.secondaryCivilIDField;
            }
            set
            {
                this.secondaryCivilIDField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "updateCreditCardCustomerProfile", WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class updateCreditCardCustomerProfileRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 0)]
        public CreditCardUpdateProfileService.creditCardCustomerProfileDTO creditCardCustomerProfileDTO;

        public updateCreditCardCustomerProfileRequest()
        {
        }

        public updateCreditCardCustomerProfileRequest(CreditCardUpdateProfileService.creditCardCustomerProfileDTO creditCardCustomerProfileDTO)
        {
            this.creditCardCustomerProfileDTO = creditCardCustomerProfileDTO;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "updateCreditCardCustomerProfileResponse", WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class updateCreditCardCustomerProfileResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 0)]
        public CreditCardUpdateProfileService.creditCardResultDTO updateCreditCardCustomerProfileResult;

        public updateCreditCardCustomerProfileResponse()
        {
        }

        public updateCreditCardCustomerProfileResponse(CreditCardUpdateProfileService.creditCardResultDTO updateCreditCardCustomerProfileResult)
        {
            this.updateCreditCardCustomerProfileResult = updateCreditCardCustomerProfileResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "insertCreditCardCustomerProfile", WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class insertCreditCardCustomerProfileRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 0)]
        public CreditCardUpdateProfileService.creditCardCustomerProfileDTO creditCardCustomerProfileDTO;

        public insertCreditCardCustomerProfileRequest()
        {
        }

        public insertCreditCardCustomerProfileRequest(CreditCardUpdateProfileService.creditCardCustomerProfileDTO creditCardCustomerProfileDTO)
        {
            this.creditCardCustomerProfileDTO = creditCardCustomerProfileDTO;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "insertCreditCardCustomerProfileResponse", WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class insertCreditCardCustomerProfileResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openuri.org/", Order = 0)]
        public CreditCardUpdateProfileService.creditCardResultDTO insertCreditCardCustomerProfileResult;

        public insertCreditCardCustomerProfileResponse()
        {
        }

        public insertCreditCardCustomerProfileResponse(CreditCardUpdateProfileService.creditCardResultDTO insertCreditCardCustomerProfileResult)
        {
            this.insertCreditCardCustomerProfileResult = insertCreditCardCustomerProfileResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface CreditCardUpdateProfileServicesServiceChannel : CreditCardUpdateProfileService.CreditCardUpdateProfileServicesService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class CreditCardUpdateProfileServicesServiceClient : System.ServiceModel.ClientBase<CreditCardUpdateProfileService.CreditCardUpdateProfileServicesService>, CreditCardUpdateProfileService.CreditCardUpdateProfileServicesService
    {

        public CreditCardUpdateProfileServicesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<CreditCardUpdateProfileService.getCreditCardCustomerProfileResponse> getCreditCardCustomerProfileAsync(CreditCardUpdateProfileService.getCreditCardCustomerProfileRequest request)
        {
            return base.Channel.getCreditCardCustomerProfileAsync(request);
        }

        public System.Threading.Tasks.Task<CreditCardUpdateProfileService.performAccountBoardResponse> performAccountBoardAsync(CreditCardUpdateProfileService.performAccountBoardRequest request)
        {
            return base.Channel.performAccountBoardAsync(request);
        }

        public System.Threading.Tasks.Task<CreditCardUpdateProfileService.updateCreditCardNoAndFDAcctNoResponse> updateCreditCardNoAndFDAcctNoAsync(CreditCardUpdateProfileService.updateCreditCardNoAndFDAcctNoRequest request)
        {
            return base.Channel.updateCreditCardNoAndFDAcctNoAsync(request);
        }

        public System.Threading.Tasks.Task<CreditCardUpdateProfileService.updateCreditCardCustomerNoResponse> updateCreditCardCustomerNoAsync(CreditCardUpdateProfileService.updateCreditCardCustomerNoRequest request)
        {
            return base.Channel.updateCreditCardCustomerNoAsync(request);
        }

        public System.Threading.Tasks.Task<CreditCardUpdateProfileService.updateCreditCardAndProfileResponse> updateCreditCardAndProfileAsync(CreditCardUpdateProfileService.updateCreditCardAndProfileRequest request)
        {
            return base.Channel.updateCreditCardAndProfileAsync(request);
        }

        public System.Threading.Tasks.Task<CreditCardUpdateProfileService.deleteCreditCardCustomerProfileResponse> deleteCreditCardCustomerProfileAsync(CreditCardUpdateProfileService.deleteCreditCardCustomerProfileRequest request)
        {
            return base.Channel.deleteCreditCardCustomerProfileAsync(request);
        }

        public System.Threading.Tasks.Task<CreditCardUpdateProfileService.updateCreditCardCustomerProfileResponse> updateCreditCardCustomerProfileAsync(CreditCardUpdateProfileService.updateCreditCardCustomerProfileRequest request)
        {
            return base.Channel.updateCreditCardCustomerProfileAsync(request);
        }

        public System.Threading.Tasks.Task<CreditCardUpdateProfileService.insertCreditCardCustomerProfileResponse> insertCreditCardCustomerProfileAsync(CreditCardUpdateProfileService.insertCreditCardCustomerProfileRequest request)
        {
            return base.Channel.insertCreditCardCustomerProfileAsync(request);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
