//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticDataInquiriesServiceReference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class Exception
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.openuri.org/", ConfigurationName="StaticDataInquiriesServiceReference.StaticDataInquiriesService")]
    public interface StaticDataInquiriesService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/StaticDataInquiriesService/translateTextRequest", ReplyAction="http://www.openuri.org/StaticDataInquiriesService/translateTextResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StaticDataInquiriesServiceReference.Exception), Action="http://www.openuri.org/StaticDataInquiriesService/translateText/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StaticDataInquiriesServiceReference.translateTextResponse> translateTextAsync(StaticDataInquiriesServiceReference.translateTextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/StaticDataInquiriesService/getValueByClientAndServiceAndAt" +
            "tributeRequest", ReplyAction="http://www.openuri.org/StaticDataInquiriesService/getValueByClientAndServiceAndAt" +
            "tributeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StaticDataInquiriesServiceReference.Exception), Action="http://www.openuri.org/StaticDataInquiriesService/getValueByClientAndServiceAndAt" +
            "tribute/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StaticDataInquiriesServiceReference.getValueByClientAndServiceAndAttributeResponse> getValueByClientAndServiceAndAttributeAsync(StaticDataInquiriesServiceReference.getValueByClientAndServiceAndAttributeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/StaticDataInquiriesService/getAccountDefinitionsRequest", ReplyAction="http://www.openuri.org/StaticDataInquiriesService/getAccountDefinitionsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StaticDataInquiriesServiceReference.Exception), Action="http://www.openuri.org/StaticDataInquiriesService/getAccountDefinitions/Fault/Exc" +
            "eption", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StaticDataInquiriesServiceReference.getAccountDefinitionsResponse> getAccountDefinitionsAsync(StaticDataInquiriesServiceReference.getAccountDefinitionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/StaticDataInquiriesService/getChargeAmountByServiceNameReq" +
            "uest", ReplyAction="http://www.openuri.org/StaticDataInquiriesService/getChargeAmountByServiceNameRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StaticDataInquiriesServiceReference.Exception), Action="http://www.openuri.org/StaticDataInquiriesService/getChargeAmountByServiceName/Fa" +
            "ult/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StaticDataInquiriesServiceReference.getChargeAmountByServiceNameResponse> getChargeAmountByServiceNameAsync(StaticDataInquiriesServiceReference.getChargeAmountByServiceNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/StaticDataInquiriesService/getTransactionMatrixValueReques" +
            "t", ReplyAction="http://www.openuri.org/StaticDataInquiriesService/getTransactionMatrixValueRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(StaticDataInquiriesServiceReference.Exception), Action="http://www.openuri.org/StaticDataInquiriesService/getTransactionMatrixValue/Fault" +
            "/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StaticDataInquiriesServiceReference.getTransactionMatrixValueResponse> getTransactionMatrixValueAsync(StaticDataInquiriesServiceReference.getTransactionMatrixValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/StaticDataInquiriesService/getValueByServiceAndAttributeRe" +
            "quest", ReplyAction="http://www.openuri.org/StaticDataInquiriesService/getValueByServiceAndAttributeRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StaticDataInquiriesServiceReference.Exception), Action="http://www.openuri.org/StaticDataInquiriesService/getValueByServiceAndAttribute/F" +
            "ault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StaticDataInquiriesServiceReference.getValueByServiceAndAttributeResponse> getValueByServiceAndAttributeAsync(StaticDataInquiriesServiceReference.getValueByServiceAndAttributeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/StaticDataInquiriesService/getAppConfigByKeyRequest", ReplyAction="http://www.openuri.org/StaticDataInquiriesService/getAppConfigByKeyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StaticDataInquiriesServiceReference.getAppConfigByKeyResponse> getAppConfigByKeyAsync(StaticDataInquiriesServiceReference.getAppConfigByKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/StaticDataInquiriesService/getChargeByServiceAndCategoryRe" +
            "quest", ReplyAction="http://www.openuri.org/StaticDataInquiriesService/getChargeByServiceAndCategoryRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StaticDataInquiriesServiceReference.Exception), Action="http://www.openuri.org/StaticDataInquiriesService/getChargeByServiceAndCategory/F" +
            "ault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StaticDataInquiriesServiceReference.getChargeByServiceAndCategoryResponse> getChargeByServiceAndCategoryAsync(StaticDataInquiriesServiceReference.getChargeByServiceAndCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/StaticDataInquiriesService/clearIntegrationCacheRequest", ReplyAction="http://www.openuri.org/StaticDataInquiriesService/clearIntegrationCacheResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StaticDataInquiriesServiceReference.clearIntegrationCacheResponse> clearIntegrationCacheAsync(StaticDataInquiriesServiceReference.clearIntegrationCacheRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="translateText", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class translateTextRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=1)]
        public bool isFromEnglishToArabic;
        
        public translateTextRequest()
        {
        }
        
        public translateTextRequest(string text, bool isFromEnglishToArabic)
        {
            this.text = text;
            this.isFromEnglishToArabic = isFromEnglishToArabic;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="translateTextResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class translateTextResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string translateTextResult;
        
        public translateTextResponse()
        {
        }
        
        public translateTextResponse(string translateTextResult)
        {
            this.translateTextResult = translateTextResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValueByClientAndServiceAndAttribute", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getValueByClientAndServiceAndAttributeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string clientName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=1)]
        public string serviceName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=2)]
        public string attributeName;
        
        public getValueByClientAndServiceAndAttributeRequest()
        {
        }
        
        public getValueByClientAndServiceAndAttributeRequest(string clientName, string serviceName, string attributeName)
        {
            this.clientName = clientName;
            this.serviceName = serviceName;
            this.attributeName = attributeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValueByClientAndServiceAndAttributeResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getValueByClientAndServiceAndAttributeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string getValueByServiceAndAttributeResult;
        
        public getValueByClientAndServiceAndAttributeResponse()
        {
        }
        
        public getValueByClientAndServiceAndAttributeResponse(string getValueByServiceAndAttributeResult)
        {
            this.getValueByServiceAndAttributeResult = getValueByServiceAndAttributeResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openuri.org/")]
    public partial class accountDefinitionBean
    {
        
        private string definitionIdField;
        
        private string arabicDescriptionField;
        
        private string englishDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string definitionId
        {
            get
            {
                return this.definitionIdField;
            }
            set
            {
                this.definitionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string arabicDescription
        {
            get
            {
                return this.arabicDescriptionField;
            }
            set
            {
                this.arabicDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string englishDescription
        {
            get
            {
                return this.englishDescriptionField;
            }
            set
            {
                this.englishDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountDefinitions", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getAccountDefinitionsRequest
    {
        
        public getAccountDefinitionsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountDefinitionsResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getAccountDefinitionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AccountDefinitionDTO")]
        public StaticDataInquiriesServiceReference.accountDefinitionBean[] getAccountDefinitionsResult;
        
        public getAccountDefinitionsResponse()
        {
        }
        
        public getAccountDefinitionsResponse(StaticDataInquiriesServiceReference.accountDefinitionBean[] getAccountDefinitionsResult)
        {
            this.getAccountDefinitionsResult = getAccountDefinitionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getChargeAmountByServiceName", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getChargeAmountByServiceNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string serviceName;
        
        public getChargeAmountByServiceNameRequest()
        {
        }
        
        public getChargeAmountByServiceNameRequest(string serviceName)
        {
            this.serviceName = serviceName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getChargeAmountByServiceNameResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getChargeAmountByServiceNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public double getChargeAmountByServiceNameResult;
        
        public getChargeAmountByServiceNameResponse()
        {
        }
        
        public getChargeAmountByServiceNameResponse(double getChargeAmountByServiceNameResult)
        {
            this.getChargeAmountByServiceNameResult = getChargeAmountByServiceNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTransactionMatrixValue", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getTransactionMatrixValueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string transactionType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=1)]
        public string serviceName;
        
        public getTransactionMatrixValueRequest()
        {
        }
        
        public getTransactionMatrixValueRequest(string transactionType, string serviceName)
        {
            this.transactionType = transactionType;
            this.serviceName = serviceName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTransactionMatrixValueResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getTransactionMatrixValueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string getTransactionMatrixValueResult;
        
        public getTransactionMatrixValueResponse()
        {
        }
        
        public getTransactionMatrixValueResponse(string getTransactionMatrixValueResult)
        {
            this.getTransactionMatrixValueResult = getTransactionMatrixValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValueByServiceAndAttribute", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getValueByServiceAndAttributeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string serviceName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=1)]
        public string attributeName;
        
        public getValueByServiceAndAttributeRequest()
        {
        }
        
        public getValueByServiceAndAttributeRequest(string serviceName, string attributeName)
        {
            this.serviceName = serviceName;
            this.attributeName = attributeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValueByServiceAndAttributeResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getValueByServiceAndAttributeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string getValueByServiceAndAttributeResult;
        
        public getValueByServiceAndAttributeResponse()
        {
        }
        
        public getValueByServiceAndAttributeResponse(string getValueByServiceAndAttributeResult)
        {
            this.getValueByServiceAndAttributeResult = getValueByServiceAndAttributeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAppConfigByKey", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getAppConfigByKeyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getAppConfigByKeyRequest()
        {
        }
        
        public getAppConfigByKeyRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAppConfigByKeyResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getAppConfigByKeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string getAppConfigByKey;
        
        public getAppConfigByKeyResponse()
        {
        }
        
        public getAppConfigByKeyResponse(string getAppConfigByKey)
        {
            this.getAppConfigByKey = getAppConfigByKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getChargeByServiceAndCategory", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getChargeByServiceAndCategoryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public string serviceName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=1)]
        public string categoryName;
        
        public getChargeByServiceAndCategoryRequest()
        {
        }
        
        public getChargeByServiceAndCategoryRequest(string serviceName, string categoryName)
        {
            this.serviceName = serviceName;
            this.categoryName = categoryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getChargeByServiceAndCategoryResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class getChargeByServiceAndCategoryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        public double getChargeByServiceAndCategoryResult;
        
        public getChargeByServiceAndCategoryResponse()
        {
        }
        
        public getChargeByServiceAndCategoryResponse(double getChargeByServiceAndCategoryResult)
        {
            this.getChargeByServiceAndCategoryResult = getChargeByServiceAndCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="clearIntegrationCache", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class clearIntegrationCacheRequest
    {
        
        public clearIntegrationCacheRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="clearIntegrationCacheResponse", WrapperNamespace="http://www.openuri.org/", IsWrapped=true)]
    public partial class clearIntegrationCacheResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.openuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clearIntegrationCacheResult;
        
        public clearIntegrationCacheResponse()
        {
        }
        
        public clearIntegrationCacheResponse(string clearIntegrationCacheResult)
        {
            this.clearIntegrationCacheResult = clearIntegrationCacheResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface StaticDataInquiriesServiceChannel : StaticDataInquiriesServiceReference.StaticDataInquiriesService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class StaticDataInquiriesServiceClient : System.ServiceModel.ClientBase<StaticDataInquiriesServiceReference.StaticDataInquiriesService>, StaticDataInquiriesServiceReference.StaticDataInquiriesService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public StaticDataInquiriesServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(StaticDataInquiriesServiceClient.GetBindingForEndpoint(endpointConfiguration), StaticDataInquiriesServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StaticDataInquiriesServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(StaticDataInquiriesServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StaticDataInquiriesServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(StaticDataInquiriesServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StaticDataInquiriesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<StaticDataInquiriesServiceReference.translateTextResponse> translateTextAsync(StaticDataInquiriesServiceReference.translateTextRequest request)
        {
            return base.Channel.translateTextAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaticDataInquiriesServiceReference.getValueByClientAndServiceAndAttributeResponse> getValueByClientAndServiceAndAttributeAsync(StaticDataInquiriesServiceReference.getValueByClientAndServiceAndAttributeRequest request)
        {
            return base.Channel.getValueByClientAndServiceAndAttributeAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaticDataInquiriesServiceReference.getAccountDefinitionsResponse> getAccountDefinitionsAsync(StaticDataInquiriesServiceReference.getAccountDefinitionsRequest request)
        {
            return base.Channel.getAccountDefinitionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaticDataInquiriesServiceReference.getChargeAmountByServiceNameResponse> getChargeAmountByServiceNameAsync(StaticDataInquiriesServiceReference.getChargeAmountByServiceNameRequest request)
        {
            return base.Channel.getChargeAmountByServiceNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaticDataInquiriesServiceReference.getTransactionMatrixValueResponse> getTransactionMatrixValueAsync(StaticDataInquiriesServiceReference.getTransactionMatrixValueRequest request)
        {
            return base.Channel.getTransactionMatrixValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaticDataInquiriesServiceReference.getValueByServiceAndAttributeResponse> getValueByServiceAndAttributeAsync(StaticDataInquiriesServiceReference.getValueByServiceAndAttributeRequest request)
        {
            return base.Channel.getValueByServiceAndAttributeAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaticDataInquiriesServiceReference.getAppConfigByKeyResponse> getAppConfigByKeyAsync(StaticDataInquiriesServiceReference.getAppConfigByKeyRequest request)
        {
            return base.Channel.getAppConfigByKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaticDataInquiriesServiceReference.getChargeByServiceAndCategoryResponse> getChargeByServiceAndCategoryAsync(StaticDataInquiriesServiceReference.getChargeByServiceAndCategoryRequest request)
        {
            return base.Channel.getChargeByServiceAndCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaticDataInquiriesServiceReference.clearIntegrationCacheResponse> clearIntegrationCacheAsync(StaticDataInquiriesServiceReference.clearIntegrationCacheRequest request)
        {
            return base.Channel.clearIntegrationCacheAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.StaticDataInquiriesServiceSoap2))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.StaticDataInquiriesServiceSoap5))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.StaticDataInquiriesServiceSoap6))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.StaticDataInquiriesServiceSoap3))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.StaticDataInquiriesServiceSoap4))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.StaticDataInquiriesServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.StaticDataInquiriesServiceSoap2))
            {
                return new System.ServiceModel.EndpointAddress("https://integration/ws/WLS_StaticDataInquiriesService/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.StaticDataInquiriesServiceSoap5))
            {
                return new System.ServiceModel.EndpointAddress("https://integration/kfhsoa/ws/StaticDataInquiriesService/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.StaticDataInquiriesServiceSoap6))
            {
                return new System.ServiceModel.EndpointAddress("https://soa_apigw/kfhsoa/ws/StaticDataInquiriesService/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.StaticDataInquiriesServiceSoap3))
            {
                return new System.ServiceModel.EndpointAddress("https://soa_apigw/ws/WLS_StaticDataInquiriesService.StaticDataInquiriesServiceSoa" +
                        "p/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.StaticDataInquiriesServiceSoap4))
            {
                return new System.ServiceModel.EndpointAddress("https://soa_apigw/ws/WLS_StaticDataInquiriesService/1.0");
            }
            if ((endpointConfiguration == EndpointConfiguration.StaticDataInquiriesServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://integration/ws/WLS_StaticDataInquiriesService.StaticDataInquiriesServiceS" +
                        "oap/1.0");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            StaticDataInquiriesServiceSoap2,
            
            StaticDataInquiriesServiceSoap5,
            
            StaticDataInquiriesServiceSoap6,
            
            StaticDataInquiriesServiceSoap3,
            
            StaticDataInquiriesServiceSoap4,
            
            StaticDataInquiriesServiceSoap,
        }
    }
}
